### ISSUE TITLE
Wrong colors inside tmux

### ISSUE THREAD

**Issue by rpereira** [lifepillar/vim-solarized8#1]
Hi @lifepillar,

The colors are rendered nicely outside tmux, but here's how it looks inside tmux:

![screen shot 2016-06-09 at 10 01 00](https://cloud.githubusercontent.com/assets/3859158/15924335/7593bf2a-2e29-11e6-85bf-f5a8f3fe6e87.png)

Running on a 24-bit capable terminal emulator; latest version of tmux, with the following settings:

```
set -g default-terminal "xterm-256color"
set -ga terminal-overrides ",xterm-256color:Tc"
```

Any idea what the problem might be? Thanks.

**Comment by lifepillar** [comment]
Maybe related to https://github.com/vim/vim/issues/804?

**Comment by nelsyeung** [comment]
Is this related to this? http://superuser.com/questions/399296/256-color-support-for-vim-background-in-tmux

**Comment by rpereira** [comment]
@lifepillar It might be...

@nelsyeung I don't think so. If if set `screen-256` instead of `xterm`, things become even crazier. :)

![screen shot 2016-06-09 at 22 20 46](https://cloud.githubusercontent.com/assets/3859158/15946877/ac1bb3ce-2e90-11e6-8c9a-324e8890d2b5.png)

**Comment by nelsyeung** [comment]
@ruiafonsopereira Are you sure your `TERM` variable is actually `screen-256color`, thought? I mean a lot of people set tmux default terminal to be `screen-256color` then have `export TERM=xterm-256color`, which is wrong.

If you do `echo $TERM` inside tmux with `set -g default-terminal "screen-256color"`, it should be `screen-256color`. If not, then you must have a `.bashrc` or some other start up script with the `export TERM` variable set there, or it can be in your terminal app settings as well.

I find that a lot of colour problems with tmux is to do with inconsistency between tmux `TERM` var and the actual `TERM` var. So it's worth a shot.

I don't actually have this problem with my tmux on Terminal.app and on SUSE enterprise Konsole.

**Comment by rpereira** [comment]
Hi @nelsyeung 

Thanks for pointing that out, but I actually have set the right `TERM` variable. However, my terminal app (iTerm2) reports `xterm-256` color and I can't change that to `screen`. This was never a problem until I've tried Vim and tmux with true color.

**Comment by lifepillar** [comment]
Can anyone check NeoVim with true color support enabled? ~~Colors are ok outside tmux, but they are off inside tmux.~~ With tmux configured as follows NeoVim displays colors just fine in iTerm2:

```
set -g default-terminal    "screen-256color"
set -ga terminal-overrides ",xterm-256color:Tc"
```

I suggest that we wait for https://github.com/vim/vim/issues/804 to be closed, to see whether that fixes this issue as well.

**Comment by rpereira** [comment]
Unfortunately, the issue on the vim repository doesn't seem  to get a lot of attention.

Perhaps we should wait, @lifepillar

**Comment by lifepillar** [comment]
@ruiafonsopereira The only workaround I can think of is to set your 16 terminal colors to the Solarized palette and set `notermguicolors` in `vimrc` when you are inside tmux:

```
  if has('termguicolors') && $TERM_PROGRAM ==# 'iTerm.app' && $TERM !~# '^\%(screen\|tmux\)'
    set termguicolors
  else
    set notermguicolors
  endif
```

 Or use NeoVim…

**Comment by lifepillar** [comment]
It seems that Vim p1942 fixes this problem. @ruiafonsopereira Could you please confirm that?

**Comment by rpereira** [comment]
@lifepillar 
I've seen the patch, but without changing configuration, now Vim renders everything in grey when inside Tmux if `termguicolors` is set. I'd have try and address that issue first.

**Comment by rpereira** [comment]
@lifepillar and @nelsyeung Any idea what might be or what am I missing?

![screen shot 2016-06-18 at 11 40 40](https://cloud.githubusercontent.com/assets/3859158/16170410/82c71918-3549-11e6-9552-0ab93527d2d3.png)

My configurations are the same specified on https://github.com/lifepillar/vim-solarized8/issues/1#issue-159360359

Inside tmux:

```
➔ echo $TERM
screen-256color

➔ tmux info | grep Tc
197: Tc: (flag) true
```

Thanks.

**Comment by lifepillar** [comment]
@ruiafonsopereira Yes, I had the same problem. You need to add this to your `vimrc`:

```
set t_8f=^[[38;2;%lu;%lu;%lum  " Needed in tmux
set t_8b=^[[48;2;%lu;%lu;%lum  " Ditto
```

(where `^[` is literal Esc, that you get by typing `<C-V><C-[>`). See `:h xterm-true-color` for the details.

**Comment by rpereira** [comment]
My bad. I was experimenting and changed “;” to “:” and forgot to revert. Problem solved. Thanks @lifepillar
.

**Comment by vprasanth** [comment]
> https://github.com/tmux/tmux/issues/696

The comment regarding properly overriding was my problem. Maybe that will help anyone who still is having the colours look funky within tmux.
