### ISSUE TITLE
No italic font for comments in GNU Screen (dev version 4.99)

### ISSUE THREAD

**Issue by boxofgit** [lifepillar/vim-solarized8#100]
I tried solarized8 with _XTerm_ and _ST_ (suckless simple terminal), and 24bit colorscheme _solarized8_ works good. Here few lines of my _~/.vimrc_:

```
" Truecolor support
set termguicolors

" Fix truecolor for ST teminal
" set Vim-specific sequences for RGB colors
let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"

" Enable syntax and scheme solarized8 dark
syntax enable
set background=dark
colorscheme solarized8
```
With the above config, _solarized8_ colorscheme appears properly as in screenshots found on this project pages.
But...
If I open for instance XTerm, then run "screen session", something appears different:
colors seem OK as in regular XTerm, but where there was text in Italic font, here in screen appears changed to "regular font".
In _solarized8_ italic font is used for comments, and running Vim within an XTerm or ST terminal comments actually appear in italic, while within a Screen session not.

[GNU Screen](https://www.gnu.org/software/screen/) supports truecolor but only in [its development version (master branch)](https://git.savannah.gnu.org/cgit/screen.git/tree/).
I built it and it pass various 24bit tests... it can output all rainbow colors just like XTerm or ST.
Here a working really basic _~/.screenrc_:
```
truecolor on
term screen.xterm-256color
```

I also tried Italic fonts from shell within Screen by using escape sequences:
```
echo -e "\e[1mbold\e[0m"
echo -e "\e[3mitalic\e[0m"
echo -e "\e[3m\e[1mbold italic\e[0m"
echo -e "\e[4munderline\e[0m"
echo -e "\e[9mstrikethrough\e[0m"
``````
And are all working (except for the last one, _strikethrough_). So I would expect comments drawn with Italic  font also in Vim... but seems something prevents it.

Any chance to fix this?
Thanks in advance!

**Comment by lifepillar** [comment]
What does `:echo &t_ZH` print when you execute it from a Vim instance inside a Screen session, and when you execute it from a Vim session in your local terminal?

**Comment by boxofgit** [comment]
It returns
```
^[[7m
```
whit the first "^[" as the same returned by "CTRL+v ESC".

Anyway I found a [solution for  tmux](https://gist.github.com/gutoyr/4192af1aced7a1b555df06bd3781a722?permalink_comment_id=4103962) and maybe I understood a bit more about terminals italic capabilities.

Both XTerm and ST terminal emulators have "ritm" and "sitm" defined in their _terminfo_, while Screen seem to lack them:
```
$ infocmp st-256color | grep itm
        ri=\EM, ritm=\E[23m, rmacs=\E(B, rmcup=\E[?1049l,
        sgr0=\E[0m, sitm=\E[3m, smacs=\E(0, smcup=\E[?1049h,
$ infocmp xterm-256color | grep itm
        rev=\E[7m, ri=\EM, rin=\E[%p1%dT, ritm=\E[23m, rmacs=\E(B,
        sgr0=\E(B\E[m, sitm=\E[3m, smacs=\E(0, smam=\E[?7h,
$ infocmp screen-256color | grep itm
$
```
The idea explained in the above link is to add in screen-256color terminfo.
```
sitm=\E[3m, ritm=\E[23
```
After that, italic fonts appear properly also in Vim, without any need to add to _~/.vimrc_ a remap for _t_ZH_ and _t_ZR_ as suggested in that link:
```
set t_ZH=^[[3m
set t_ZR=^[[23m
```

As recap:

1. Create a temp file named for instance _screen-256color.terminfo_ with the following content:
```
# A screen-256color based TERMINFO that adds the escape sequences for italic.
#
# Install:
#
#   tic screen-256color.terminfo
#
# Usage:
#
#   export TERM=screen-256color
#
screen-256color|screen with 256 colors and italic,
        sitm=\E[3m, ritm=\E[23m,
        use=screen-256color,
```
2.    Execute the command:
```
$ tic screen-256color.terminfo
```
And it is "compiled" and written in _~/.terminfo/s/screen-256color_. And it is recall before the system wide original version _/usr/share/terminfo/s/screen-256color_. 
As an alternative should be possible to create a new  terminfo file with a new name, such as _screen-256 by changing the first above line as follows:
```
screen-256color-italic|screen with 256 colors and italic,
```
To use it, ensure screen is started with $TERM coherently defined by adding to _~/.screenrc_:
```
term screen-256color-italic
```
Anyway in conclusion terminfo results as follow:
```
$ infocmp screen-256color-italic
#       Reconstructed via infocmp from file: /home/simpleuser/.terminfo/s/screen-256color-italic
screen-256color-italic|screen with 256 colors and italic,
        am, km, mir, msgr, xenl,
        colors#0x100, cols#80, it#8, lines#24, pairs#0x10000,
        acsc=++\,\,--..00``aaffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz{{||}}~~,
        bel=^G, blink=\E[5m, bold=\E[1m, cbt=\E[Z, civis=\E[?25l,
        clear=\E[H\E[J, cnorm=\E[34h\E[?25h, cr=\r,
        csr=\E[%i%p1%d;%p2%dr, cub=\E[%p1%dD, cub1=^H,
        cud=\E[%p1%dB, cud1=\n, cuf=\E[%p1%dC, cuf1=\E[C,
        cup=\E[%i%p1%d;%p2%dH, cuu=\E[%p1%dA, cuu1=\EM,
        cvvis=\E[34l, dch=\E[%p1%dP, dch1=\E[P, dim=\E[2m,
        dl=\E[%p1%dM, dl1=\E[M, ed=\E[J, el=\E[K, el1=\E[1K,
        enacs=\E(B\E)0, flash=\Eg, home=\E[H, hpa=\E[%i%p1%dG,
        ht=^I, hts=\EH, ich=\E[%p1%d@, il=\E[%p1%dL, il1=\E[L,
        ind=\n, indn=\E[%p1%dS, is2=\E)0, kbs=^H, kcbt=\E[Z,
        kcub1=\EOD, kcud1=\EOB, kcuf1=\EOC, kcuu1=\EOA,
        kdch1=\E[3~, kend=\E[4~, kf1=\EOP, kf10=\E[21~,
        kf11=\E[23~, kf12=\E[24~, kf2=\EOQ, kf3=\EOR, kf4=\EOS,
        kf5=\E[15~, kf6=\E[17~, kf7=\E[18~, kf8=\E[19~, kf9=\E[20~,
        khome=\E[1~, kich1=\E[2~, kmous=\E[M, knp=\E[6~, kpp=\E[5~,
        nel=\EE, op=\E[39;49m, rc=\E8, rev=\E[7m, ri=\EM,
        rin=\E[%p1%dT, ritm=\E[23m, rmacs=^O, rmcup=\E[?1049l,
        rmir=\E[4l, rmkx=\E[?1l\E>, rmso=\E[23m, rmul=\E[24m,
        rs2=\Ec\E[?1000l\E[?25h, sc=\E7,
        setab=\E[%?%p1%{8}%<%t4%p1%d%e%p1%{16}%<%t10%p1%{8}%-%d%e48;5;%p1%d%;m,
        setaf=\E[%?%p1%{8}%<%t3%p1%d%e%p1%{16}%<%t9%p1%{8}%-%d%e38;5;%p1%d%;m,
        sgr=\E[0%?%p6%t;1%;%?%p1%t;3%;%?%p2%t;4%;%?%p3%t;7%;%?%p4%t;5%;%?%p5%t;2%;m%?%p9%t\016%e\017%;,
        sgr0=\E[m\017, sitm=\E[3m, smacs=^N, smcup=\E[?1049h,
        smir=\E[4h, smkx=\E[?1h\E=, smso=\E[3m, smul=\E[4m,
        tbc=\E[3g, u6=\E[%i%d;%dR, u7=\E[6n, u8=\E[?1;2c, u9=\E[c,
        vpa=\E[%i%p1%dd,
```

After this configuration, as a check test if I open vim and echo the following:
```
:echo &t_ZH
```
it returns:
```
^[[3m
```
and not _^[[7m_, as before.

OK, hope it helps also some other Screen users to let solarized8 color scheme working properly in their multiplexer session.

**Comment by lifepillar** [comment]
Great you've found a way to fix it yourself. Thanks for the reporting such a detailed explanation!

For completeness: afaik (I am not an expert) there is not standard way to detect “italic support” in a terminal. If you look at the source code of this color scheme, what this color scheme does is checking that `t_ZH` is not empty and is not `^[[7m`, in which case it adds italic attributes to some highlight groups. This is obviously a hack, but it seems to work in the most common cases.

If there are better ways, I'd like to know!

**Comment by boxofgit** [comment]
I'm really far from being an expert too!
Just searched and tried with a bit of luck... Anyway as far as I know your colorscheme should be OK, but with Screen and its default terminfo definitions it doesn't work as expected. I don't know if it is better to edit Screen terminfo as I did or try to find a better hack within your solarized8 theme.
Anyway seems Screen terminfo lacks also other features compared to XTerm or ST, for instance _strikethrough_ as I yet reported in my first message:
```
$ echo -e "\e[9mstrikethrough\e[0m
```
It appears properly with XTerm and ST, but does not if tested in a Screen session. Just an example not strictly related to Vim and its themes.
