### ISSUE TITLE
E423: Illegal argument: ctermul=160 cterm=undercurl

### ISSUE THREAD

**Issue by gennaro-tedesco** [lifepillar/vim-solarized8#103]
After the latest commits I am seeing an exception while loading the plugin via lazy package manager, in particular
```lua
E5113: Error while calling lua chunk: vim/_meta.lua:0

nvim_exec2() called at ~/.config/nvim/init.lua:0..~/.local/share/nvim/lazy/vim-solarized8/colors/solarized8_flat.vim, line 480: Vim(highlight):E423: Illegal argument: ctermul=160 cterm=undercurl
# stacktrace:
  - vim/_editor.lua:0 _in_ **cmd**
  - ~/.config/nvim/init.lua:40 _in_ **init**
  - ~/.config/nvim/init.lua:454%
  ```
may this be anything introduced by the latest changes?

**Comment by mooreye** [comment]
Same for me in neovim v0.9.0

**Comment by lifepillar** [comment]
Neovim does not support the `ctermul` attribute. The solution for now is to downgrade to v1.4.0 of this colorscheme. I need to think about how to address these kind of incompatibilities: I'm tempted to split this project into a version for Neovim and a version for Vim: features are diverging  more and more…

**Comment by mooreye** [comment]
Thank you, `git reset --hard v1.4.0` fixed it for me, for now

**Comment by lifepillar** [comment]
That is fixed in master. Please reopen if that does not work for you.
