### ISSUE TITLE
tmux configuration notes in neovim README

### ISSUE THREAD

**Issue by skyvine** [lifepillar/vim-solarized8#106]
Hello,

I recently noticed the 1.5.1-neovim branch and looked at the differences to see if there was anything I should change in my configuration. I noticed the removal of the "troubleshooting" section. I assume that this was removed because the (neo)vim variables `t_8f` and `t_8b` do not need to be set when using neovim. However, the tmux configuration noted there is still needed. I am concerned that neovim users may not see this note in the vim branch. Would you consider restoring the tmux configuration notes to the README, even though the vim variables do not need to be set?

Regards,
Skyler

**Comment by lifepillar** [comment]
Thanks for pointing that out! I've reinstated the troubleshooting section, except for the `t_xx` settings.
