### ISSUE TITLE
Render bold and italic for Neorg

### ISSUE THREAD

**Issue by krzkrzkrz** [lifepillar/vim-solarized8#108]
Using the following colorscheme in [Neorg](https://github.com/nvim-neorg/neorg), does not render bold or italic.

Typing: `hi @neorg.markup.bold` and `:hi @neorg.markup.italic`, returns:

```
@neorg.markup.bold xxx links to @text.strong
@neorg.markup.italic xxx links to @text.emphasis
```

However, `vim-solarized8/colors/solarized8.vim` doesnt implement highlights for `@text.strong` and `@text.emphasis`

The solution would be to add the following highlights somewhere in this file `/colors/solarized8.vim`:

```
hi @text.strong guifg=fg guibg=NONE gui=bold cterm=bold
hi @text.emphasis guifg=fg guibg=NONE gui=italic cterm=italic
```

Adding above to the theme definition, renders bold and italics

Refer to the before screenshot:
<img width="272" alt="before" src="https://github.com/lifepillar/vim-solarized8/assets/390072/3647a236-f942-4389-86c0-5e6c9eeea43a">

And after screenshot:
<img width="360" alt="after" src="https://github.com/lifepillar/vim-solarized8/assets/390072/8ff9fb22-8366-4979-b22c-0e6881474488">

Reference: https://github.com/nvim-neorg/neorg/issues/644

**Comment by krzkrzkrz** [comment]
Alternatively, adding this to `after/plugin/vim-solarized8.lua`:

```
vim.cmd([[autocmd ColorScheme * highlight @text.strong guifg=fg guibg=NONE gui=bold cterm=bold]])
vim.cmd([[autocmd ColorScheme * highlight @text.emphasis guifg=fg guibg=NONE gui=italic cterm=italic]])
```

Does the trick too. But checking to see if this is the right approach

**Comment by lifepillar** [comment]
This should be fixed in HEAD (make sure you checkout the `neovim` branch).

Are `@text.strong` and `@text.emphasis` documented somewhere? Does Neovim define other `@`-groups?
