### ISSUE TITLE
Comments look weird in tmux

### ISSUE THREAD

**Issue by mooreye** [lifepillar/vim-solarized8#109]
For example my Sway config file, the comments are highlighted like this:
![image](https://github.com/lifepillar/vim-solarized8/assets/93423596/8923dd86-2fb4-4623-a40b-91ad34230b89)

Normally outside tmux, they look like this:

![image](https://github.com/lifepillar/vim-solarized8/assets/93423596/840e75ca-329b-4da4-89db-d7b6e6fc273a)

I'm using `neovim` branch.

I'm already using this: https://github.com/lifepillar/vim-solarized8#troubleshooting

The AWK thing shows proper fullcolor support in tmux:
![image](https://github.com/lifepillar/vim-solarized8/assets/93423596/70761618-3935-427d-b50e-04ff37512a04)

```
Fedora 38
NVIM v0.9.1
GNOME Terminal 3.48.1
```

**Comment by mooreye** [comment]
Solved it by setting 
`set -g  default-terminal   'tmux-256color'`
in tmux config, instead of `screen-256color` like your README says.

Source: https://unix.stackexchange.com/questions/745710/getting-italics-working-correctly-in-tmux

Can you verify and rectify?

**Comment by lifepillar** [comment]
That makes sense: I have updated the Readme. Thanks!
