### ISSUE TITLE
Notice of breaking changes: treesitter

### ISSUE THREAD

**Issue by gennaro-tedesco** [lifepillar/vim-solarized8#113]
I want to bring to your attention the [latest breaking changes](https://github.com/nvim-treesitter/nvim-treesitter/issues/2293#issuecomment-1900679583) on nvim-treesitter. [This commit](https://github.com/nvim-treesitter/nvim-treesitter/commit/1ae9b0e4558fe7868f8cda2db65239cfb14836d0) changes names of many highlight groups, as a consequence colour schemes may have to adapt if possible.

**Comment by lifepillar** [comment]
Thanks! Solarized 8 currently uses only `@text.strong` and `@text.emphasis`, which I have updated to `@markup.strong` and `@markup.emphasis`, respectively.

As I am not using Neovim myself, I accept PRs for other highlight groups: the file to modify is `_neovim.colortemplate` (in the `neovim` branch).
