### ISSUE TITLE
Breaking changes: Neovim 0.10.0

### ISSUE THREAD

**Issue by JKThanassi** [lifepillar/vim-solarized8#114]
It looks like the [new version of neovim](https://neovim.io/doc/user/news-0.10.html) has changed the default colorscheme which is breaking solarized8. See the `Defaults` block on the release notes for details.

Below is a screenshot of my editor with solarized8 in light mode. As you can see, many of the color values are no longer correct.

<img width="275" alt="image" src="https://github.com/lifepillar/vim-solarized8/assets/10533698/9c33690c-2c07-4eea-8983-72ba1eea53db">

Would it be possible for the theme to be updated to account for the new defaults?

**Comment by lifepillar** [comment]
I have added the missing definitions mentioned in the release notes you've linked, but since I don't use Neovim, I have not tested them. Feel free to open another issue if some tweaks are needed, but please specify which highlight groups are affected and how they should be defined.
