### ISSUE TITLE
I can not install a theme?

### ISSUE THREAD

**Issue by gHashTag** [lifepillar/vim-solarized8#12]
.vimrc:
```
Plug 'lifepillar/vim-solarized8'
colorscheme solarized8_dark
```
As a result, this result:
![2017-04-23 11 51 30](https://cloud.githubusercontent.com/assets/6774813/25312184/7b1d5bbc-281b-11e7-839c-98e26f9e63c8.png)
Why?

**Comment by lifepillar** [comment]
Most likely, your terminal does not support true colors. As such, you should define the terminal ANSI palette to match the Solarized scheme.
