### ISSUE TITLE
Why are not the correct colors in Neovim?

### ISSUE THREAD

**Issue by gHashTag** [lifepillar/vim-solarized8#13]
![2017-04-27 15 51 27](https://cloud.githubusercontent.com/assets/6774813/25484129/676f0f04-2b61-11e7-821b-6eb57d3f6ebf.png)

**Comment by lifepillar** [comment]
Please provide more details (OS, terminal) and a step-by-step procedure to reproduce.

**Comment by lifepillar** [comment]
Closing as I didn't get any more feedback. Feel free to re-open with more details if you haven't been able to fix this issue.
