### ISSUE TITLE
light version's cursor is bad

### ISSUE THREAD

**Issue by vdrandom** [lifepillar/vim-solarized8#14]
The cursor of the light version of the theme does not provide enough contrast between the background and the foreground (black on blue):
```
hi! Cursor cterm=NONE gui=NONE ctermfg=8 guifg=#002b36 ctermbg=4 guibg=#268bd2
```

I, personally, prefer these colors (red just works better):
```
hi! Cursor cterm=NONE gui=NONE ctermfg=15 guifg=#fdf6e3 ctermbg=1 guibg=#dc322f
```

But setting the foreground to white would be enough to make the cursor less tiring:
```
hi! Cursor cterm=NONE gui=NONE ctermfg=15 guifg=#fdf6e3 ctermbg=4 guibg=#268bd2
```

**Comment by lifepillar** [comment]
Which terminal are you using?

**Comment by vdrandom** [comment]
The issue is clearly present in gvim.

I haven't noticed it before because I mostly use vim in a terminal (rxvt-unicode in my case), so this has nothing to do with a terminal emulator.

**Comment by lifepillar** [comment]
Ok, I see, the commit that introduced that was a mistake. The original Solarized uses:

```
hi! Cursor gui=NONE guifg=#fdf6e3 guibg=#657b83
```

I am thinking to revert to the original Solarized choice, possibly using red for the high contrast variant. What do you think?

**Comment by vdrandom** [comment]
This cursor is functional (even though I do prefer red). Using red for high contrast variant seems reasonable (keep in mind I don't have much experience using high contrast variant, however).

Considering this was the default it's not that hard to see why there was an issue with a “jumping cursor” on MatchParen, by the way.

**Comment by lifepillar** [comment]
I am closing this because the cursor's default color has been changed to orange in the light normal variant and to red in the high contrast variant.

>Considering this was the default it's not that hard to see why there was an issue with a “jumping cursor” on MatchParen, by the way.

Agree. The discussion on `MatchParen` continues at https://github.com/lifepillar/vim-solarized8/issues/15.

**Edit:** orange -> red
