### ISSUE TITLE
Cursor is the wrong color

### ISSUE THREAD

**Issue by frioux** [lifepillar/vim-solarized8#17]
Feel free to reject this.  I used solarized for ages before switching to this and the few changes I've noticed (especially the matchparen change) are improvements, *except* that in the original solarized the block cursor was always white, and here it is simply an inverted block.  Was that on purpose?  I find it distracting.

**Comment by lifepillar** [comment]
Just to be clear, the cursor does not invert any color: in the default variant, it's always white text on blue background in the dark version, and white text on red background in the light version.

I may add an option to keep the original Solarized colors for the cursor. Would that be fine with you?

**Comment by frioux** [comment]
Yeah I don't mind tweaking an option; I just know the skittles-flavored-cursor distracts me :)

**Comment by lifepillar** [comment]
Please pull the current master, and put this in your `vimrc`:

```vim
let g:solarized_old_cursor_style = 1
```

**Comment by frioux** [comment]
I updated to 2210b20 and set g:solarized_old_cursor_style to 1 as instructed, but it looks exactly the same?  Here's a screenshot, just to show the invert issue I'm talking about:

![zfp-selection-119](https://user-images.githubusercontent.com/8163/27918731-ad95a2aa-6224-11e7-9037-0eb6a2b5b950.png)

I can't figure out how to get the screenshot when it's active, but I think this get's the point across; the cursor is neither white nor grey, but the color of the text that it's on top of.

**Comment by lifepillar** [comment]
Which Vim are you using (terminal/gui), and on which platform? By default, the cursor in `solarized8_dark` looks like this (screenshot from MacVim):

<img width="199" alt="blue-cursor" src="https://user-images.githubusercontent.com/1193314/27919325-b08fd74e-6271-11e7-9b98-12577a1d2a84.png">

With `g:solarized_old_cursor_style` on, it looks like this:

<img width="202" alt="grey-cursor" src="https://user-images.githubusercontent.com/1193314/27919344-c155cfa2-6271-11e7-8610-70662f8835ee.png">

If you are using Vim in some terminal, the cursor appearance most likely depends on the terminal settings.

**Comment by frioux** [comment]
Ok, I didn't know that.  I'm using vim8 in Terminator on Linux (Ubuntu.)  I clicked around and figured out that you're right, I just needed to tweak the color in the terminal settings.  Thanks!

**Comment by lifepillar** [comment]
Good to know. I think it is a good idea to have an option to customise the cursor's appearance anyway.

For the sake of completeness and for future reference, in GUI Vim the cursor of `solarized8_light` looks like this by default:

<img width="199" alt="cursor-light" src="https://user-images.githubusercontent.com/1193314/27976107-6ecf9e26-6365-11e7-9010-ceecdcfcde1e.png">

When `g:solarized_old_cursor_style` is on, it looks like this instead:

<img width="200" alt="cursor-light-old" src="https://user-images.githubusercontent.com/1193314/27976114-79210874-6365-11e7-8331-7403b970280e.png">
