### ISSUE TITLE
Any plan to support coloring php docblock?

### ISSUE THREAD

**Issue by rawaludin** [lifepillar/vim-solarized8#18]
I see there's no highlighting for php docblock https://phpdoc.org/docs/latest/guides/docblocks.html. Any plan to support it? 

Thanks.

**Comment by lifepillar** [comment]
Text like:

```php
/**
  * Returns the name of this object.
  *
  * @return string
  */
```

is highlighted as a comment, and `@return` is recognized as `phpDocTags`. Please provide more details on how to reproduce the issue if you cannot fix it.

**Comment by rawaludin** [comment]
I'm getting this

<img width="805" alt="screen shot 2017-07-30 at 8 10 03 pm" src="https://user-images.githubusercontent.com/1274849/28753749-3c926668-7563-11e7-91ae-9113adec6876.png">

<img width="911" alt="screen shot 2017-07-30 at 8 12 32 pm" src="https://user-images.githubusercontent.com/1274849/28753758-785440ea-7563-11e7-9852-af1b04c5a728.png">

I'm on iterm2 3.1.beta4, using solarized8_dark theme, default solarized theme on iterm2.

Thanks

**Comment by lifepillar** [comment]
What does `:verbose hi phpDocTags` report?

**Comment by rawaludin** [comment]
```
:verbose hi phpDocTags
phpDocTags     xxx links to phpComment
        Last set from ~/dotfiles/.config/nvim/plugged/vim-polyglot/syntax/php.vim
```

Turn out vim-polyglot causing this. If I remove that plugin, highlighting worked.

**Comment by lifepillar** [comment]
I suspected something like that. Also the `function` keyword is highlighted differently in your setup (it should be red).

Closing this as this is to be reported elsewhere.
