### ISSUE TITLE
Improve ruby highlighting 

### ISSUE THREAD

**Issue by amerov** [lifepillar/vim-solarized8#19]
![selection_098](https://user-images.githubusercontent.com/196747/31045439-50cfd7da-a5fd-11e7-9d8c-ef22451e5a62.png)

**Comment by lifepillar** [comment]
What are the other colorschemes?

**Comment by amerov** [comment]
@lifepillar  jellybeans and monokain

**Comment by lifepillar** [comment]
Can you try the current master and report how it works for you?

**Comment by amerov** [comment]
![selection_099](https://user-images.githubusercontent.com/196747/31046741-89d84a66-a617-11e7-9bbd-e776d7238b3c.png)

**Comment by lifepillar** [comment]
Does that solve your issue?

**Comment by amerov** [comment]
I think it is better than old version :+1:

**Comment by lifepillar** [comment]
Ok, so I'm closing this. Feel free to reopen if you need to provide more feedback!
