### ISSUE TITLE
Vim completion list non-highlighted item unreadable in solarized8_dark

### ISSUE THREAD

**Issue by vivekvjn** [lifepillar/vim-solarized8#20]
The color for non-selected items in the drop-down needs to be more readable.
![vimcomplete](https://user-images.githubusercontent.com/6826760/31947543-7507d224-b8cc-11e7-8229-82cea649c345.PNG)

**Comment by lifepillar** [comment]
Your colors look wrong. It looks like you are not using a terminal supporting true colors and you have not set the terminal palette to Solarized. The completion menu should look like this:

<img width="764" alt="solarized_complete" src="https://user-images.githubusercontent.com/1193314/31966542-52fc0b0c-b90b-11e7-8e10-6801092a56b2.png">

**Comment by vivekvjn** [comment]
Yeah looks like. I was using WSL bash terminal and changed some parameters which might have mixed up. Seems to work fine after a re-login. Please close the issue.
