### ISSUE TITLE
Error since latest commit

### ISSUE THREAD

**Issue by Konfekt** [lifepillar/vim-solarized8#22]
On Vim 8.603 with the light scheme, since the latest commits, there appears at the start of Vim the error message 
```vim
Error detected while processing function <SNR>251_set_highlight_colors[37]..<SNR>251_add_to_highlight_group:
line    1:
E417: missing argument: ctermbg=
Error detected while processing function <SNR>251_set_highlight_colors[38]..<SNR>251_add_to_highlight_group:
line    1:
E417: missing argument: ctermbg=
Press ENTER or type command to continue
```
probably introduced by

a22a0c688eaa24bbdc5c3a3eb762e2d9ecbe7dd8

**Comment by Konfekt** [comment]
Upon inspection, it is probably an error of quick-scope
```vim
sourcing "/home/konfekt/.vim/plugged/quick-scope/plugin/quick_scope.vim"
                                                                    Error detected while processing function <SNR>251_set_highlight_colors[37]..<SNR>251_add_to_highlight_group:
line    1:
E417: missing argument: ctermbg=
Error detected while processing function <SNR>251_set_highlight_colors[38]..<SNR>251_add_to_highlight_group:
line    1:
E417: missing argument: ctermbg=
```

**Comment by lifepillar** [comment]
Make sure you are using the current master. I have moved away from the messy source Vim script to use [Colortemplate](https://github.com/lifepillar/vim-colortemplate) to generate the colorschemes. Along the way, I may have pushed unstable commits.

**Comment by Konfekt** [comment]
Ok. It was a known issue by this plugin. Switching to the maintained version https://github.com/bradford-smith94/quick-scope resolved the problem.
