### ISSUE TITLE
termguicolors

### ISSUE THREAD

**Issue by Konfekt** [lifepillar/vim-solarized8#24]
The check
```vim
!(has('termguicolors') && &termguicolors)
```
produces with Vim 8.603 with `notermguicolors` set the error cmessage
```vim
colors/solarized8_dark.vim:
line   11:
[Solarized8 Dark] There are not enough colors.
```

However, before, when the check is disabled (as used to be the case in 2e4943cbe1c2aaaeb960a522e96305d0242d1d61) the colors show up just fine.

Under URxvt, what settings must be used for the coloring with `termguicolors` set to show up fine?

**Comment by lifepillar** [comment]
What does `echo &t_Co` print when you get that error?

**Comment by lifepillar** [comment]
Also, does setting `let g:solarized_use16 = 0` before loading the colorscheme result in the expected outcome?

I see now that there is an inconsistent default value for such setting. I will fix it.

**Comment by lifepillar** [comment]
>Under URxvt, what settings must be used for the coloring with `termguicolors` set to show up fine?

Does URxvt support true colors? IIRC, it does not. With terminal supporting only 256 colors, you should not set `termiguicolors`: you must either set the terminal 16 ANSI colors to Solarized, or put `let g:solarized_use16 = 0` in your `vimrc` to use a (very crude) approximate palette.

**Comment by Konfekt** [comment]
Yes, thank you! I did not see this setting. With `let g:solarized_use16 = 0` everything works as before. A couple of commits ago, before https://github.com/lifepillar/vim-solarized8/commit/2e4943cbe1c2aaaeb960a522e96305d0242d1d61, this was apparently not necessary.

**Comment by Konfekt** [comment]
And no, URxvt does not support true colors, from what I saw.

**Comment by lifepillar** [comment]
>A couple of commits ago, before 2e4943c, this was apparently not necessary.

The setting should not be necessary now either: that's a bug, which I plan to fix soon.

In the future, however, I might switch to using the degraded 256-color palette by default on non-true color terminals, in which case, if you want to use your terminal's 16 ANSI colors instead, you will have to change the setting explicitly.

**Comment by lifepillar** [comment]
>there is an inconsistent default value for `g:solarized_use16`.

This is fixed. Please note that now Solarized 8 falls back to using an approximate 256 color palette when true colors are not available (because that is the less unpredictable color palette). So, if you want to fall back to your 16 terminal colors instead, you still need to set `g:solarized_use16` to `0`.
