### ISSUE TITLE
Add colorization for warning and errors

### ISSUE THREAD

**Issue by amerov** [lifepillar/vim-solarized8#25]
![screenshot from 2017-11-10 20-28-32](https://user-images.githubusercontent.com/196747/32665366-c846942a-c655-11e7-9737-b30cd482a82b.png)

Example with spelling

**Comment by lifepillar** [comment]
Not sure everyone would like the “colorization” you suggest. Would it be ok if that would be enabled with `let g:solarized_visibility = "high"`?
