### ISSUE TITLE
Only getting 256 colors

### ISSUE THREAD

**Issue by amkirwan** [lifepillar/vim-solarized8#26]
Update recently to`neovim 0.2.1` and now only 256 colors are loading. 

Running with following setup:

- neovim 0.2.1 *homebrew install*
- iterm2 3.1.5
- OS X 10.12.6
- zsh

**Comment by lifepillar** [comment]
~~I see. But I can reproduce with other colorschemes, too. It is either a regression in NeoVim, or something has changed and some settings must be tweaked. For instance, I see that NeoVim has `termguicolors` as well—have you tried setting `termguicolors` in your `vimrc`?~~

**Edit:** I was testing with Terminal.app.

**Comment by lifepillar** [comment]
Oops, sorry, I was testing in Terminal.app. I have tried iTerm2 (3.1.1) and NeoVim 0.2.1, and colors look right. You are not using ssh or tmux, are you?

**Comment by lifepillar** [comment]
It seems that you need `set termguicolors` in your `vimrc`, after all. Can you confirm?

**Comment by amkirwan** [comment]
sure will try `set termguicolors` 

I did just checkout tag `v0.8` and colors are working again

**Comment by lifepillar** [comment]
>I did just checkout tag v0.8 and colors are working again

That's likely because your terminal is configured to use the Solarized palette (v0.8 did not fall back to a 256-color palette, but to the terminal's 16 ANSI colors).

**Comment by amkirwan** [comment]
Yeah `set termquicolors` worked

**Comment by amkirwan** [comment]
thanks for the help!

**Comment by lifepillar** [comment]
Thanks for the report. I have updated the Readme to clarify that `termguicolors` must be set in NeoVim, too.
