### ISSUE TITLE
Always getting light background

### ISSUE THREAD

**Issue by coding-chimp** [lifepillar/vim-solarized8#27]
I recently updated to v1.0.1 and now I'm always getting the light background.

I'm running with following setup:

- neovim 0.2.0
- iTerm2 3.1.5
- OS X 10.12.6
- zsh

And the relevant part of my vimrc looks like this:

```
set termguicolors
set background=dark
colorscheme solarized8
```

**Comment by coding-chimp** [comment]
After a bit of debuggin I found the following:

For some reason the code is triggered twice. Not sure if this is normal.
In the first run the background is switched to light on [this line](https://github.com/lifepillar/vim-solarized8/blob/master/colors/solarized8.vim#L50). On the second run it'll then use the light colors.

**Comment by lifepillar** [comment]
How did you debug that? That line cannot possibly set the background to light. But I have noticed a difference between Vim and NeoVim. After this command:

```
vim -N --noplugin -n -i NONE -u NONE --cmd 'set termguicolors' --cmd 'set bg=dark' --cmd 'colorscheme solarized8'
```

`:set bg?` returns `dark`, while after running NeoVim with the same options:

```
nvim -N --noplugin -n -i NONE -u NONE --cmd 'set termguicolors' --cmd 'set bg=dark' --cmd 'colorscheme solarized8'
```

`:set bg?` returns `light`. It happens with other colorschemes as well, but not with all of those I have tried.

It looks like a bug in NeoVim to me.

**Comment by coding-chimp** [comment]
I just echoed the background throughout the file and narrowed it down to this line. When I change `ctermbg` to `NONE` in this line it works.

So yeah, this makes no sense and is almost definitely a bug in NeoVim. Thanks anyway! 🙂

**Comment by lifepillar** [comment]
Ah, you are right! I can fix it, too, by setting `ctermbg` to `NONE`.

Please link to this issue if you open a NeoVim's issue, as a reference for future visitors.

**Comment by hasseio** [comment]
I'm suffering from this issue, and not sure how to fix while being on stable neovim. Is there anything I can add to my init.vim to work around this issue for now?

**Comment by lifepillar** [comment]
Put this in your `virmc`:

```vim
let g:solarized_termtrans=1
```

That will set a transparent background, but it should work around this issue.

**Comment by hasseio** [comment]
Cheers mate.
