### ISSUE TITLE
problem with tmux and true color (termguicolors)

### ISSUE THREAD

**Issue by gigi206** [lifepillar/vim-solarized8#28]
Hello,

Congratulations for your work. I try to migrate official Solarized to your Solarized8 but I encounter a problem with comments with tmux (tc enabled) :
```
$ tmux info | grep Tc    
 197: Tc: (flag) true
```
All colors are printed correctly inside tmux.

Without tmux comments are printed correctly :
![capture d ecran de 2017-11-26 18-52-25](https://user-images.githubusercontent.com/13576579/33242844-5309ee40-d2db-11e7-83ec-9fa573d51e03.png)

Inside tmux comment are not printed correctly :
![capture d ecran de 2017-11-26 18-52-39](https://user-images.githubusercontent.com/13576579/33242846-572dc33e-d2db-11e7-91b3-e6a3d65ac9fa.png)

Do you know how to correct this problem ?

**Comment by lifepillar** [comment]
The likely reason why comments have the wrong highlighting is that the terminfo entry used by tmux does not support italics, which Solarized 8 uses by default.

**Edit:** what does `echo $TERM` print inside tmux?

So, the following line in your `vimrc` should fix it:

```vim
let g:solarized_term_italics=0
```

If you want to keep italics, you have to change tmux's terminal. Depending on your setup, you may want to copy the file `tmux-256color` from ncurses's ~source code~ distribution into your `~/.terminfo` directory (I have it in `~/.terminfo/t/tmux-256color` under Linux, and in `~/.terminfo/74/tmux-256color` under macOS). Then, you should update your `.tmux.conf` accordingly:

```
set -g  default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color:Tc"
```

If `tmux-256color` already exists in your system, you might only need to update `.tmux.conf`.

**Comment by gigi206** [comment]
I change screen-256color to tmux-256color for default-terminal variabe in .tmux.conf file and it solved the problem.

Thank you very much for your help :)

**Comment by lifepillar** [comment]
Solarized 8 now has italics disabled by default. So, you should not get comments with a gray background even if you use your old settings.
