### ISSUE TITLE
Comments have gray background after update

### ISSUE THREAD

**Issue by dwayneyuen** [lifepillar/vim-solarized8#29]
Here's an example (the first line):
![screen shot 2017-11-29 at 10 16 27 am](https://user-images.githubusercontent.com/1113568/33391590-6869951e-d4ee-11e7-89f7-421842bf39e3.png)

![screen shot 2017-11-29 at 10 18 54 am](https://user-images.githubusercontent.com/1113568/33391728-bc0106b2-d4ee-11e7-8bf5-63ed234a2e2b.png)

I just updated using https://github.com/junegunn/vim-plug and now my comments have a light gray background (vimrc, python files). Is this intended? The screenshots in the README don't have it, and in the past that wasn't the case.

My settings:
```
let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
colorscheme solarized8
set termguicolors
```

```
$ vim --version
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jul 24 2017 13:14:56)
MacOS X (unix) version
Included patches: 1-740
Compiled by Homebrew
```

I am using iTerm2:
![screen shot 2017-11-29 at 10 17 45 am](https://user-images.githubusercontent.com/1113568/33391661-90a9e1b4-d4ee-11e7-852e-98b2fefe3dd3.png)

Please let me know if I can provide any more helpful information! Thank you for the great plugin!

**Comment by lifepillar** [comment]
See https://github.com/lifepillar/vim-solarized8/issues/28. You should disable italics.

Since I've got already two issues in a few days about this, I think I will revert to having italics disabled by default.

**Comment by lifepillar** [comment]
Please try the current master. I have reverted to not using italics by default. Let me know if it fixes your issue.

**Comment by dwayneyuen** [comment]
That fixed it for me. That was incredibly fast, thanks for your help! Next time I'll try to look around in past issues more carefully. Thank you!

**Comment by lifepillar** [comment]
Good to know!

**Comment by CaioBianchi** [comment]
I'm having the same issue, with Italics disabled.

**Comment by lifepillar** [comment]
OS? Terminal?

**Comment by CaioBianchi** [comment]
macOS High Sierra
iTerm2

Only happens within Tmux + Neovim

**Comment by CaioBianchi** [comment]
And yes, I do have

```
let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
```

in my `.vimrc` file

**Comment by lifepillar** [comment]
I cannot reproduce it. The only thing that may be different in my system is that I use a custom terminfo file. You may try copying the `dot-terminfo` folder from https://github.com/lifepillar/dotfiles into `~/.terminfo` and set the terminal accordingly in `.tmux.conf`:

```
set -g default-terminal "tmux-256color"
```

Do you stil have the issue?
