### ISSUE TITLE
A question 

### ISSUE THREAD

**Issue by ghost** [lifepillar/vim-solarized8#30]
Hi there. 
Thanks for developing! I think it's the best solarized colorcheme for Vim.
But I didn't open a new issue just for say thank you.
Actually I read ReadMe.md file and you said: 

> Set your terminal's 16 ANSI colors (the colors in the range 0–15) to the Solarized palette. Most terminals allow you to do that: see the manual of your terminal to learn how. Then, put this line in your vimrc before loading the colorscheme

 but I confused about ANSI colors and my question is why (& when) I should use 
`let g:solarized_use16 = 1` in my vimrc?
NOTE that I set `tgc` option in my vimrc.

**Comment by lifepillar** [comment]
>my question is why (& when) I should use let `g:solarized_use16 = 1` in my vimrc?

Only if all these conditions are satisfied:

1. your terminal does not support true colors, but only 256 colors;
2. you still want to get the exact Solarized palette, not an approximation;
3. your terminal already uses the  Solarized palette.

If you have set `tgc` and the colors look right, you are likely using a true-color terminal, so no other configuration is needed.

**Comment by ghost** [comment]
Thanks for your quick respon. 
Hope to continue developing this great theme.
Good luck.

**Comment by ghost** [comment]
I'm sorry for reopening this issue.
Is it important to `set bg=dark` for this colorsheme?
Because as far as I know solarized8 isn't a dark colorcheme to set `bg` option to 'dark'.

**Comment by lifepillar** [comment]
Solarized 8 has both dark and light variants. So, yes, you should set `background` before loading the colorscheme because Solarized 8 adapts to the current value of `background`.

**Comment by ghost** [comment]
Thanks 👍
