### ISSUE TITLE
My Colors are broken (fallback to 16color when I have 256color + italics)

### ISSUE THREAD

**Issue by IanEdington** [lifepillar/vim-solarized8#31]
In order to get tmux and iterm 2.2 working together with italics `xterm-256color-italic` has been adopted to indicate a terminal with color and italics. Is there a way to support this in solarized8?

Or give a flag to force 256 color on a terminal that solarized8 doesn't recognize as having 256 color?

**Comment by lifepillar** [comment]
Solarized 8 falls back to using a 256 color palette *unless* `g:solarized_use16` is set to `1`. Since you are running inside tmux, my guess is that you have a different issue. Please provide the relevant part of your Vim settings, in particular the value of `termguicolors`, `t_8f`, `t_8b`, `t_Co` and `term`. Is “iterm“ iTerm2 on macOS or another terminal emulator? Which version of tmux are you using?

**Comment by IanEdington** [comment]
> Is “iterm“ iTerm2 on macOS or another terminal emulator? Which version of tmux are you using?

yes

`g:solarized_use16` is not set in my vim config

> Since you are running inside tmux, my guess is that you have a different issue.

The colors work properly in `vim-solarized8` version 0.8

> Please provide the relevant part of your Vim settings, in particular the value of...

Not sure if this is what you're looking for:
- `set termguicolors` isn't defined
- `let t_8f` isn't defined
- `let t_8b` isn't defined
- `let t_Co` isn't defined
- `let term` isn't defined

Is there any other info you would like to know?
Thank you

**Comment by lifepillar** [comment]
To print the value of an option, please use `set`, not `let`, e.g.:

```vim
:set termguicolors?
:set t_8f?
```

iTerm2 supports true colors (unless you are using an old version), so you should put `set termguicolors` in your `vimrc`. No fallback will happen then.  If you still see the wrong colors inside tmux, please read the Troubleshooting section in the Readme. Also, see https://github.com/lifepillar/vim-solarized8/issues/28. Let me know if that helps.

**Comment by lifepillar** [comment]
Btw:

>In order to get tmux and iterm 2.2 working together with italics xterm-256color-italic has been adopted to indicate a terminal with color and italics.

Are you sure that `xterm-256color-italic` exists in your system?

>Is there a way to support this in solarized8?

With a true-color enabled terminal like iTerm2, Solarized 8 uses GUI colors, not 256 or 16 colors (but you must set `termguicolors`). To enable italics, you must put this in your `vimrc`:

```vim
let g:solarized8_term_italics = 1
```

Your terminal font must have italics, of course, and tmux must also be configured accordingly (again, see https://github.com/lifepillar/vim-solarized8/issues/28).

**Comment by IanEdington** [comment]
Fantastic thank you very much for your help. I’ll try this today and make a
comment on how goes.

**Comment by IanEdington** [comment]
`:set termguicolors?` =  `notermguicolors`
`:set t_8f?` = `E846: Key code not set: t_8f?`

`set termguicolors` worked for me.
