### ISSUE TITLE
incorrect colors on startup

### ISSUE THREAD

**Issue by kebolio** [lifepillar/vim-solarized8#33]
![2018-01-28-182033_971x292_scrot](https://user-images.githubusercontent.com/22417496/35485478-37309a8a-0458-11e8-9377-e29093dd5e45.png)
on the left is vim directly after startup, and on the right is having run `colo solarized8` again. `g:solarized_use16` is set to 1. i've tried `autocmd VimEnter colorscheme solarized8` but it produces the same results.

**Comment by lifepillar** [comment]
What happens with `vim --clean  -c 'set bg=dark' -c 'colo solarized8'`?

**Comment by IngoMeyer441** [comment]
@kebolio Are you using neovim? I have the same problem in neovm, even with a minimal `.vimrc`:
```vim
set nocompatible
syntax enable
colorscheme solarized8
set background=dark
```
However, this minimal `.vimrc` works for original vim. If `colorscheme` and `set background` are swapped, the colors are fine in neovim:
```vim
set nocompatible
syntax enable
set background=dark
colorscheme solarized8
```
@kebolio Can you confirm this?

**Comment by lifepillar** [comment]
Thanks @IngoHeimbach, now I see the problem. That looks like a bug in NeoVim. But, it's a good idea to set the background *before* loading the colorscheme anyway. @kebolio: does that solve your issue?

**Comment by IngoMeyer441** [comment]
Btw: [Similar issues have been discussed for rakr's colorscheme one](https://github.com/rakr/vim-one/issues/50#issuecomment-304618662).

**Comment by kebolio** [comment]
sorry i've been and am too busy to sort this one out

**Comment by kebolio** [comment]
well funnily enough i switched around from using vim in xterm on arch linux to vim in gnome-terminal on ubuntu 17.10 and it works just fine. i'll try replicating it again once i have the time

**Comment by lifepillar** [comment]
Ok, so for now I am closing this, as it does not appear to be an issue with the colorscheme. Feel free to re-open if necessary!
