### ISSUE TITLE
[Solarized 8] There are not enough colors.

### ISSUE THREAD

**Issue by chenyangguang** [lifepillar/vim-solarized8#35]
.vimrc 
```
let g:solarized_use16 = 0
let g:solarized_termcolors=256
colorscheme solarized8
```

[Solarized 8] There are not enough colors.

**Comment by lifepillar** [comment]
Solarized 8 does not use `g:solarized_termcolors`: you may remove that line.

What is the output of `:set t_Co?`. With your settings (which are the default, btw), you need at least 256 colors. If this doesn't help, please provide more details (OS, Vim version, terminal, whether you are using tmux).

**Comment by chenyangguang** [comment]
@lifepillar , 

`:set t_co` 

![image](https://user-images.githubusercontent.com/7223579/37343374-49e5a900-2702-11e8-8086-e369e808a516.png)

**Comment by lifepillar** [comment]
As the error message says, there are not enough colors. You may try:

```vim
set t_Co=256
```

in your `vimrc`. If that does not work, you will need to:

1. set your terminal colors to Solarized;
2. put `let g:solarized_use16 = 1` in your `vimrc`.

For (1), see your terminal's documentation.

**Comment by chenyangguang** [comment]
My .vimrc config like  this: 

if has('gui_running')
    set background=light
else
    set background=dark
endif
"let g:solarized_use16 = 0
set t_Co=256
let g:solarized_termcolors=256
colorscheme solarized8

Now it works well. But i have a doubt that it has no diffrent from solarized8 to solarize. Anyway, many thanks for @lifepillar

**Comment by lifepillar** [comment]
Good to know that it works for you now!
