### ISSUE TITLE
Won't load dark theme in NeoVim

### ISSUE THREAD

**Issue by kyla963** [lifepillar/vim-solarized8#36]
Hello, I have successfully used this theme in MacVim, but upon switching to NeoVim, while the light theme loads automatically, I have to :source ~/.vimrc every time, when I do it switches to dark mode with no issue. Hoping it would help I already added:
let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
But it did not make a difference. I'm stumped. Ideas?

I've tried using other theme and dark mode seems to load fine. Though I have not experimented with many.

**Comment by lifepillar** [comment]
Does https://github.com/lifepillar/vim-solarized8/issues/27 help?

**Comment by lifepillar** [comment]
Closing for lack of feedback (I assume that https://github.com/lifepillar/vim-solarized8/issues/27 solved your issue as well).
