### ISSUE TITLE
Python: same color for scripts and comment lines starting with # 

### ISSUE THREAD

**Issue by WeiliWw** [lifepillar/vim-solarized8#37]
Have seen this problem since the ancient solarized.  
When setting `background` to `dark`, in Python files there is always the same color for scripts and comment lines starting with `#`.  This seems to be ubiquitous in Mac/Ubuntu terminals.

<img width="638" alt="screen shot 2018-03-15 at 6 43 11 pm" src="https://user-images.githubusercontent.com/12888473/37494838-f7563c06-2880-11e8-9e16-d1ef8f11f84f.png">

My `.vimrc`:
```
set tabstop=4       " The width of a TAB is set to 4.
set shiftwidth=4    " Indents will have a width of 4
set softtabstop=4   " Sets the number of columns for a TAB
set expandtab       " Expand TABs to spaces
set hlsearch

execute pathogen#infect()

" automatic indentation
filetype indent plugin on

" let g:solarized_termcolors=256
" This block is for colors-polarized
syntax enable
set background=dark
colorscheme solarized8_high

let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
```

Did I miss something?

**Comment by lifepillar** [comment]
It looks like you are using Vim in a terminal not supporting true colors, so Solarized is falling back to using a 256-color approximation. That said, even in that approximation a comment should be a darker grey than normal text. Can you please report the output of the following commands?

```vim
:hi Normal
:hi Comment
```

**Comment by WeiliWw** [comment]
Thanks for the quick response! This is what I got:
```
:hi Normal
Normal         xxx ctermfg=247 ctermbg=235 guifg=#93a1a1 guibg=#002b36
:hi Comment
Comment        xxx term=bold ctermfg=243 gui=italic guifg=#657b83
```

**Comment by lifepillar** [comment]
Those values are correct. Does `:hi pythonComment` link to `Comment`?

**Comment by WeiliWw** [comment]
Yes
```
:hi pythonComment
pythonComment  xxx links to Comment
```

**Comment by lifepillar** [comment]
Can you try to update the comment's foreground?

```vim
:hi! Comment ctermfg=242
:hi! Comment ctermfg=102
:hi! Comment ctermfg=241
```

Can you distinguish comments better with any of these? Which one does look better?

**Comment by WeiliWw** [comment]
Seems none of them makes a difference...

**Comment by lifepillar** [comment]
Have you set `termguicolors`? If so, that may be the problem. Try:

```vim
:set notermguicolors
```

**Comment by WeiliWw** [comment]
No, I didn't set that parameter. `:set notermguicolors` doesn't help either. I was wrong in the first post, this problem only occurs in my Mac OS. In Ubuntu, comments and scripts can be distinguished easily.

**Comment by lifepillar** [comment]
Which terminal? If it's Terminal.app or iTerm2, have you tried different profiles? I'm short of ideas, but that seems a terminal issue specific to your configuration. I have no issues with either terminal.

**Comment by WeiliWw** [comment]
Yes I use iTerm2. I just tried different profiles and it seems profiles do not make a difference on vim but the 'contrast' does! If I set it to minimum contrast I can tell the difference between the scripts and comments. I guess this is the way to go... Thanks!
