### ISSUE TITLE
Using iterm2 and still getting the "crude approximation" terminal colors

### ISSUE THREAD

**Issue by dopey** [lifepillar/vim-solarized8#38]
iterm2: 3.1.5
neovim: 0.2.0

If I run `scripts/solarized8.sh` then the colors become correct for that tab. But, given that iterm2 has truecolor enabled by default, based on the README documentation it seems my configuration should work without needing to adjust the colors.

Relevant section of `.vimrc`:
```
set termguicolors
set background=dark
colorscheme solarized8_flat
```

**Comment by lifepillar** [comment]
Correct, you don't need to run any script in iTerm2.

I cannot reproduce your issue with your minimal `vimrc`. The only problem is that NeoVim loads the light colorscheme, but that's a NeoVim issue (see https://github.com/lifepillar/vim-solarized8/issues/27 and https://github.com/lifepillar/vim-solarized8/issues/36).

The only difference wrt your setup is that I use NeoVim 0.2.2.

You aren't running inside tmux, are you?

**Comment by dopey** [comment]
Sorry for letting this get away from me a bit.

Not running in tmux. Just updated to neovim 0.2.2_1 to check if behavior changed. Still getting the weird chocolatey dark instead of solarized. Here is my paired down vimrc:

```
if has('nvim')
    set runtimepath^=~/.vim runtimepath+=~/.vim/after
    let &packpath = &runtimepath
endif

" =============================================================================
" Pathogen
" =============================================================================
call pathogen#runtime_append_all_bundles()
call pathogen#helptags()

syntax on
set background=dark
colorscheme solarized8
```

**Comment by dopey** [comment]
Scratch that. Forgot to use

```
set termguicolors
```
after update to neovim 0.2.2_1. Working now. Thanks!

**Comment by bigunyak** [comment]
I have the same problem. Feels like tried everything but still only get the approximate palette...
Running the `scripts/solarized8.sh` fixes the problem in current session.
My vim:
```
~ % vim --version
VIM - Vi IMproved 8.1 (2018 May 18, compiled Nov  9 2019 02:36:49)
```
iterm2: 3.3.8

Iterm is configure to report `xterm-256color`.
The entire .vimrc as it is:
```
syntax on
set termguicolors
set background=dark
colorscheme solarized8_flat
```
Could you please maybe suggest, how can I debug it to find the cause of the problem?

**Comment by bigunyak** [comment]
I think the problem comes from me using Solarized Dark colors preset in iTerm.
After reading this: https://github.com/altercation/solarized/tree/master/vim-colors-solarized#important-note-for-terminal-users
The following configuration finally works fo me:
```
set background=dark
let g:solarized_contrast = "high"
let g:solarized_termtrans = 1
colorscheme solarized
```

**Comment by lifepillar** [comment]
Based on the information you have provided, I couldn't reproduce your issue. Your `vimc` settings are correct. Anyway, glad you found a workaround!

**Comment by hunterMG** [comment]
> I think the problem comes from me using Solarized Dark colors preset in iTerm. After reading this: https://github.com/altercation/solarized/tree/master/vim-colors-solarized#important-note-for-terminal-users The following configuration finally works fo me:
> 
> ```
> set background=dark
> let g:solarized_contrast = "high"
> let g:solarized_termtrans = 1
> colorscheme solarized
> ```

You may try this:
```
set termguicolors
```
