### ISSUE TITLE
How to install this with Neovim?

### ISSUE THREAD

**Issue by anduong** [lifepillar/vim-solarized8#39]
I wonder how this can be installed with NeoVim? Can you advise?

**Comment by lifepillar** [comment]
You install this as any other plugin or colorscheme. In particular, the instructions in the Readme (see the Installation section) should definitely work for NeoVim, too. If you cannot make it work, please provide more details (NeoVim version, installation steps you followed, if you get errors, …).

**Comment by anduong** [comment]
Thanks @lifepillar for the instruction. I'm using Vim-plug to install the theme. Here is what I have done with the ~/.config/nvim/init.vim

```Vim
" Set to use truecolor
set termguicolors

" Set color theme
set background=dark
colorscheme solarized8

" Install color theme to ~/.config/nvim/colors
Plug 'lifepillar/vim-solarized8', { 'dir': '~/.config/nvim/colors/solarized8' }
```

But I got the error 
```sh
Error detected while processing /Users/an/.config/nvim/init.vim:
line    6:
E185: Cannot find color scheme 'solarized8'
```

**Comment by lifepillar** [comment]
I don't use vim-plug, but I would make two changes:

1. Set the colorscheme *after* the `Plug` command (this may matter if Solarized 8 is not installed yet).

2. Let vim-plug install Solarized 8 in the default location, i.e., use:

```vim
Plug 'lifepillar/vim-solarized8'
```

instead of

```vim
Plug 'lifepillar/vim-solarized8', { 'dir': '~/.config/nvim/colors/solarized8' }
```

**Comment by anduong** [comment]
Thanks @lifepillar. I'm going to try your suggestion 👍

**Comment by anduong** [comment]
@lifepillar I got the yellow background/screen after trying our suggestion :(
<img width="1663" alt="screen shot 2018-04-14 at 2 11 27 pm" src="https://user-images.githubusercontent.com/6139560/38765541-f2e92a14-3fed-11e8-8935-59792ff21b6a.png">

**Comment by anduong** [comment]
@lifepillar The MacOS Terminal.app does not support TrueColor I think as it works for iterm2 and tmux

**Comment by lifepillar** [comment]
Make sure `termguicolors` is not set when you are using Terminal.app (`:set notermguicolors`).

**Comment by anduong** [comment]
@lifepillar So this configuration will make the Terminal fallback to 256 colors, right?

**Comment by lifepillar** [comment]
Yes. If you don’t want the approximate palette, you may install and use the Terminal.app profile provided with the plugin. You need to set `solarized_use16` as explained in the Readme, then.

**Comment by lifepillar** [comment]
Ops, sorry, there's no Terminal.app profile in the plugin. But you may find one at the official [Solarized repo](https://github.com/altercation/solarized) (forget the installation instructions: just double click on `Solarized Dark ansi.terminal` and `Solarized Light ansi.terminal` to install them).

**Comment by anduong** [comment]
@lifepillar Great! Let's me try it. Thanks a lot :)

**Comment by lifepillar** [comment]
Btw, you may use a snippet like the following in your `vimrc` to detect whether you are using a true-color terminal or not (works for iTerm2):

```vim
  if has('termguicolors') && $COLORTERM ==# 'truecolor'
    " True-color terminal
    set termguicolors
  else
    " set notermguicolors is the default
    let g:solarized_use16 = 1  " If you want to use ANSI colors
  endif
```

**Comment by anduong** [comment]
@lifepillar Yes, I'm also writing this script myself to handle the cases. Thanks 👍

**Comment by lifepillar** [comment]
I assume you solved this. Feel free to reopen if that is not the case.

**Comment by anduong** [comment]
@lifepillar Thank you so much 😄
