### ISSUE TITLE
Change the background color of the column number 

### ISSUE THREAD

**Issue by TahaMagdy** [lifepillar/vim-solarized8#40]
Hello, how to make the background color of the relative number columns as the same as the background color of text area.

As you can see here, there are two background colors.
![screen shot 2018-04-24 at 11 51 04 pm](https://user-images.githubusercontent.com/18517169/39216012-637ddcc8-481a-11e8-9654-7c906602a774.jpg)

**Comment by TahaMagdy** [comment]
highlight clear LineNr

**Comment by lifepillar** [comment]
Maybe not what you want for other reasons, but the “flat” variant (`solarized8_flat`) sets `LineNr`'s background as you like.
