### ISSUE TITLE
the color is incorrect in Xshell?

### ISSUE THREAD

**Issue by liao20081228** [lifepillar/vim-solarized8#41]
I use the xterm of Xshell in Windows  to connect Ubuntu which is runing in a virtual machine.

I add `export TERM=xterm-256color` to `~/.bashrc`, and add
```
if has("gui_runing") 
       set background=light
 else         
       set t_Co=256                                            
       set background=dark          
endif        
         
set background=dark          
syntax enable 
colorscheme solarized8
```
to `~/.vimrc`.    it  shows the following:
![pic](http://img-blog.csdn.net/20180501163619816?watermark/2/text/Ly9ibG9nLmNzZG4ubmV0L2xpYW8yMDA4MTIyOA==/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70/gravity/SouthEast)

but is not what I want ?                     what should I do to get correct colors? Thanks !

**Comment by lifepillar** [comment]
I am not sure what your issue is: is that Vim in a remote session? Do you also use Vim locally? In that case, are colors right?

See the [Readme](https://github.com/lifepillar/vim-solarized8), the section about 256-color terminals. It appears that your terminal does not support millions of colors.

**Comment by lifepillar** [comment]
Did you fix this? If not, can you provide more details about your remote connection (e.g., is it via SSH)?

**Comment by lifepillar** [comment]
Closing for lack of feedback. Feel free to reopen if necessary.
