### ISSUE TITLE
Javascript specific color

### ISSUE THREAD

**Issue by kristijanhusak** [lifepillar/vim-solarized8#42]
Hi,

I would like to append one highlight link for javascript that https://github.com/pangloss/vim-javascript is adding.
The group is `jsFuncCall`.

Currently i have this:

![screenshot](https://i.imgur.com/ejGgnnQ.png)

But after linking `jsFuncCall` to `Function` (`hi link jsFuncCall Function`) it looks bit more readable:

![screenshot_ok](https://i.imgur.com/6wOSP6f.png)

Do you allow adding language specific highlights, or every user has to do it by themselves?

I guess we could put this into the `extra_hi_groups` part.

**Comment by lifepillar** [comment]
Sure, a pull request would be welcome!

>I guess we could put this into the `extra_hi_groups` part.

You should add a JavaScript section to `templates/_extra.colortemplate` because the colorscheme is generated automatically with [Colortemplate](https://github.com/lifepillar/vim-colortemplate). The syntax is pretty intuitive.
