### ISSUE TITLE
Possible wrong color

### ISSUE THREAD

**Issue by bertinatto** [lifepillar/vim-solarized8#44]
Hi,

First of all, thank you very much for solarized8!

I use *vim-signify* and apparently the background color is incorrect:

![screenshot_2018-07-11_16-59-53](https://user-images.githubusercontent.com/1286651/42582985-86b07356-8530-11e8-99dc-d9fde9ad7250.png)

**Comment by lifepillar** [comment]
Do you mean the background of `+` and `!` signs? If so, it is vim-signify that sets the background. Solarized8 uses the Normal background (like for `a`).

**Comment by bertinatto** [comment]
Hm, I see.

Would it be possible to change the background of `+` and of the line numbers to the lighter yellow? Just like the screenshot of the README.

Thanks!

**Comment by lifepillar** [comment]
Let me know if this helps: https://github.com/mhinz/vim-signify/issues/182.

However, @mhinz mentions at https://github.com/mhinz/vim-signify/issues/128 that this is a colorscheme issue. I don't think it is, but I'll leave this open until I've investigated further.

**Comment by mhinz** [comment]
Hi,

the `SignifySign*` groups link to the standard groups `DiffAdd`, `DiffChange`, and `DiffDelete` by default.

With no solarized8 options set, I get this:

```
:verb hi DiffAdd
DiffAdd        xxx ctermfg=106 ctermbg=254 guifg=#859900 guibg=#eee8d5 guisp=#859900
        Last set from ~/.vim/bundle/vim-solarized8/colors/solarized8.vim
```

So, it must have been set by this line:

https://github.com/lifepillar/vim-solarized8/blob/ff7ec263d934320deb9c49b2ca8af61caf072f01/colors/solarized8.vim#L499

So, yes, if you don't want to alter the `Diff*` groups, have a look at `:h signify-colors`.

HTH

**Comment by lifepillar** [comment]
@mhinz Thanks for the clarification. I do not plan to change diff groups, and `SignifySign*` does solve the problem.

**Comment by bertinatto** [comment]
@lifepillar, @mhinz: thank you for your support!

I'll close this issue as this seems to solve the problem.

**Comment by ultrox** [comment]
@lifepillar thanks for creating awesome theme.

Interestingly OP actually didn't solve his problem, he changed to another theme that same day
[here](https://github.com/bertinatto/dotfiles/commit/b6c760172c609ac0480f72b308034443e64c5a34#diff-2b0aa7ee6675f69233c68ab94934cbe5R31), I though I might get solution in his dotfiles.

To fellow googler I suggest to hack the theme, rather then vim-signify, reason being vim-signify works with most other themes I installed.

Also keep in mind I don't know other consequences of this. I'm hoping @lifepillar to give his advice.
In the mean time, just paste this to the end of your .vimrc
```
hi DiffAdd ctermfg=106 ctermbg=254 guifg=#859900 guibg=#fff guisp=#859900 cterm=NONE gui=NONE 
hi DiffChange ctermfg=136 ctermbg=236 guifg=#b58900 guibg=#fff guisp=#b58900 
hi DiffDelete cterm=bold ctermfg=160 ctermbg=236 gui=bold guifg=#dc322f guibg=#fff guisp=#b58900
```

**Comment by archon810** [comment]
`#fff` should be `#ffffff` or else vim throws an error.
