### ISSUE TITLE
Incorrect g:terminal_ansi_colors

### ISSUE THREAD

**Issue by blahgeek** [lifepillar/vim-solarized8#45]
I'm using MacVim (GUI mode, version 8.1) with `background=light`. The colors in `:terminal` seems wrong.

Here's the output of [colortest](https://gist.githubusercontent.com/lifepillar/d4acaf918ae8d9bb2cab24d62abd768c/raw/a38d1e6a5500708d1f6318660f47b7702f53e009/256-colors.pl) script inside `:terminal` (which is incorrect):

<img width="640" alt="screen shot 2018-08-22 at 13 32 55" src="https://user-images.githubusercontent.com/1308450/44444631-50cb7a00-a610-11e8-8757-677ad2cc9260.png">

The correct output should be (taken from terminal outside vim):

<img width="642" alt="screen shot 2018-08-22 at 13 33 02" src="https://user-images.githubusercontent.com/1308450/44444645-6476e080-a610-11e8-8329-6e295023a429.png">

---

```
let g:terminal_ansi_colors = ['#eee8d5', '#dc322f', '#859900', '#b58900', '#268bd2', '#d33682', '#2aa198', '#073642',
      \ '#fdf6e3', '#cb4b16', '#93a1a1', '#839496', '#657b83', '#6c71c4', '#586e75', '#002b36']
```

should be changed to

```
let g:terminal_ansi_colors = ['#073642', '#dc322f', '#859900', '#b58900', '#268bd2', '#d33682', '#2aa198', '#eee8d5',
      \ '#002b36', '#cb4b16', '#93a1a1', '#839496', '#657b83', '#6c71c4', '#586e75', '#fdf6e3']
```

**Comment by lifepillar** [comment]
Good catch, thanks!
