### ISSUE TITLE
Neovim terminal  is not showing autosuggestion using the  zsh-autosuggestions

### ISSUE THREAD

**Issue by rjshrjndrn** [lifepillar/vim-solarized8#48]
`colorscheme solarized8_dark_flat`
head commit:  9b74a5faf5f8f90f1729ef054af99072ba061985
**Current terminal**
![vim terminal](https://user-images.githubusercontent.com/2563385/46193513-10040680-c31c-11e8-8958-a54333bf24c4.png)
**Expected behaviour**
![expected behaviour](https://user-images.githubusercontent.com/2563385/46193521-14c8ba80-c31c-11e8-9c0c-098e6d422f77.png)

**Additional info**
```
~/Documents/projects/ekstep-devops(DO-163 ✗) nvim --version                                                       
NVIM v0.3.1
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wconversion -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.3.1/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by lifepillar** [comment]
With this configuration, almost identical to yours, except for the last line, I cannot reproduce it:

```
# The following lines were added by compinstall

zstyle ':completion:*' completer _expand _complete _ignored _approximate
zstyle :compinstall filename '/Users/nicola/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

source ~/.oh-my-zsh/plugins/vi-mode/vi-mode.plugin.zsh
source ~/.oh-my-zsh/lib/completion.zsh
source ~/.oh-my-zsh/lib/history.zsh
source ~/.oh-my-zsh/lib/git.zsh
source ~/.oh-my-zsh/lib/theme-and-appearance.zsh
source ~/.oh-my-zsh/themes/simple.zsh-theme
source ~/.oh-my-zsh/plugins/history-substring-search/history-substring-search.zsh
source ~/.oh-my-zsh/plugins/z/z.plugin.zsh
source /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh
```

Zsh inside a NeoVim terminal window behaves the same as in a normal terminal window. Which makes me believe that the issue is your custom zsh-autosuggestions. I have tried this in iTerm2 (macOS): which terminal and OS are you using?

**Comment by rjshrjndrn** [comment]
ter:minal [tilda](https://github.com/lanoxx/tilda) 
os: Linux work 4.18.10-arch1-1-ARCH #1 SMP PREEMPT Wed Sep 26 09:48:22 UTC 2018 x86_64 GNU/Linux
vim colorscheme: solarized8_dark_flat
I think this might because of some highlight groups?
Is your zsh-autosuggestions customized? I'm using one, which comes default with oh-my-zsh

**Comment by lifepillar** [comment]
Have you tried a different terminal? Vim instead of NeoVim? Just to narrow down the problem.

>Is your zsh-autosuggestions customized? I'm using one, which comes default with oh-my-zsh

There is no plugin inside oh-my-zsh's `custom` directory. I am using this: https://github.com/zsh-users/zsh-autosuggestions.

Btw, `solarized8_dark_flat` is deprecated and will be removed soon. Use this instead:

```vim
set background=dark
colorscheme solarized8_flat
```

**Comment by lifepillar** [comment]
Ok, I was able to reproduce your issue. It is likely a terminal issue. If you run a script to display all ansi color combinations (search for `ansi_colors.sh` in Github, for example) in a terminal window using Solarized colors, you will probably see something like this:

<img width="565" alt="screenshot 2018-09-30 at 13 52 13" src="https://user-images.githubusercontent.com/1193314/46257356-79208100-c4b8-11e8-923a-f4c864e29588.png">

Note that some of the circled cells have zero contrast. The correct display should rather look like this:

<img width="565" alt="screenshot 2018-09-30 at 13 56 53" src="https://user-images.githubusercontent.com/1193314/46257378-c00e7680-c4b8-11e8-9106-8742ee3b42e3.png">

You should check your terminal's appearance options. For example, in iTerm2 (the terminal I used for the screenshots above), there is a “Minimum contrast” slider, which I used to increase the contrast.

Alternatively, you may try to change the color used by zsh for the suggested text. I am not familiar with zsh, so I don't know whether such setting exists or where to find it.

Note that the above has nothing to do with Vim: it's the Solarized theme for my terminal.

**Comment by rjshrjndrn** [comment]
is there any way to inherit the color code/scheme which is used by the terminal. Because all other themes(default ones) are working properly.

**Comment by lifepillar** [comment]
See ~`:help g:terminal_colors`~ `:help g:terminal_ansi_colors`.

**Edit:** fix variable name.

**Comment by lifepillar** [comment]
To expand on the above, you might set `g:terminal_ansi_colors` after loading a colorscheme, to set the terminal palette as you like:

```vim
autocmd Colorscheme * let g:terminal_ansi_colors = [...]
```

**Comment by rjshrjndrn** [comment]
I couldn't find any help topic in neovim for `g:terminal_ansi_colors` .

**Comment by lifepillar** [comment]
Ah, right. NeoVim uses a distinct variable for each color: `g:terminal_color_0`, …, `g:terminal_color_15`.

**Comment by rjshrjndrn** [comment]
can you please, elaborate on what to do? because I didn't get any clues. sorry to be a noob.

**Comment by lifepillar** [comment]
Put something like this in your `vimrc`:

```vim
    fun! s:setTerminalColors()
     " Adapt the colors as you see fit
      let g:terminal_color_0='#073642'
      let g:terminal_color_1='#dc322f'
      let g:terminal_color_2='#859900'
      let g:terminal_color_3='#b58900'
      let g:terminal_color_4='#268bd2'
      let g:terminal_color_5='#d33682'
      let g:terminal_color_6='#2aa198'
      let g:terminal_color_7='#eee8d5'
      let g:terminal_color_8='#002b36'
      let g:terminal_color_9='#cb4b16'
      let g:terminal_color_10='#586e75'
      let g:terminal_color_11='#657b83'
      let g:terminal_color_12='#839496'
      let g:terminal_color_13='#6c71c4'
      let g:terminal_color_14='#93a1a1'
      let g:terminal_color_15='#fdf6e3'
    endf

    autocmd Colorscheme * call <sid>setTerminalColors()
```

>sorry to be a noob.

Never mind, everyone is at a certain point in time!

**Comment by rjshrjndrn** [comment]
```
fun! s:setTerminalColors()
 " Adapt the colors as you see fit
  let g:terminal_color_0='#000000'
  let g:terminal_color_1='#000000'
  let g:terminal_color_2='#000000'
  let g:terminal_color_3='#000000'
  let g:terminal_color_4='#000000'
  let g:terminal_color_5='#000000'
  let g:terminal_color_6='#000000'
  let g:terminal_color_7='#000000'
  let g:terminal_color_8='#000000'
  let g:terminal_color_9='#000000'
  let g:terminal_color_10='#000000'
  let g:terminal_color_11='#000000'
  let g:terminal_color_12='#000000'
  let g:terminal_color_13='#000000'
  let g:terminal_color_14='#000000'
  let g:terminal_color_15='#000000'
endf

autocmd Colorscheme * call <sid>setTerminalColors()
```

still no  use...

**Comment by lifepillar** [comment]
That means…?

**Comment by rjshrjndrn** [comment]
I changed every colour combo to 0000 is, white. But there is no change...

**Comment by lifepillar** [comment]
Have you tried reloading the colorscheme? Other than that, I don’t know what else to suggest. You may ask at NeoVim’s project.

**Comment by rjshrjndrn** [comment]
This is same with vim 8+, I installed and tried. Can you please to do that in any other terminal than iTerm?

**Comment by lifepillar** [comment]
Make sure that your terminal support millions of colors. If you use a terminal supporting only 256 colors, then changing the colors as explained above does not work.

**Comment by rjshrjndrn** [comment]
I'm using tilda, and it have 24bit support.
echo $COLORTERM
truecolor

**Comment by lifepillar** [comment]
Closing this for lack of feedback. I assume that it was determined that it is a terminal issue.

**Comment by mosheavni** [comment]
> Put something like this in your `vimrc`:
> 
> ```viml
>     fun! s:setTerminalColors()
>      " Adapt the colors as you see fit
>       let g:terminal_color_0='#073642'
>       let g:terminal_color_1='#dc322f'
>       let g:terminal_color_2='#859900'
>       let g:terminal_color_3='#b58900'
>       let g:terminal_color_4='#268bd2'
>       let g:terminal_color_5='#d33682'
>       let g:terminal_color_6='#2aa198'
>       let g:terminal_color_7='#eee8d5'
>       let g:terminal_color_8='#002b36'
>       let g:terminal_color_9='#cb4b16'
>       let g:terminal_color_10='#586e75'
>       let g:terminal_color_11='#657b83'
>       let g:terminal_color_12='#839496'
>       let g:terminal_color_13='#6c71c4'
>       let g:terminal_color_14='#93a1a1'
>       let g:terminal_color_15='#fdf6e3'
>     endf
> 
>     autocmd Colorscheme * call <sid>setTerminalColors()
> ```
> 
> > sorry to be a noob.
> 
> Never mind, everyone is at a certain point in time!

frigging life saver.
Thank you!!!!!!!
