### ISSUE TITLE
g:solarized_diffmode = "bold" not implemented

### ISSUE THREAD

**Issue by kristijanhusak** [lifepillar/vim-solarized8#49]
In the readme it says that there's an "bold" option for the `g:solarized_diffmode`. I can't find that in any of the colorschemes. Is readme outdated or there's missing code?

**Comment by lifepillar** [comment]
IIRC, in the original Solarized there was that option, but it was either not used or used only in one or two rules. There's no “bold” option for `g:solarized_diffmode` in Solarized 8. I think that the Readme should be updated.

**Comment by kristijanhusak** [comment]
Ok thanks.

**Comment by lifepillar** [comment]
Thanks for pointing out the mistake. If you have ideas for improving diff mode, feel free to open a pull request!
