### ISSUE TITLE
Invisible cursor over search term

### ISSUE THREAD

**Issue by manasthakur** [lifepillar/vim-solarized8#5]
Hi @lifepillar ,

This issue has been there for the gnome-terminal in the original solarized as well: altercation/vim-colors-solarized#167

The problem is that when we search something (with `set hlsearch`), the cursor color on the searched term is same as the background color, because of which the cursor becomes invisible. Same thing happens on the first entry in a quickfix window.

_p.s._ This does not happen in iTerm2 when smartcursor is set.

Any solutions?

**Comment by lifepillar** [comment]
Does setting the `Cursor` highlight group have any effect? For instance:

```
:hi! Cursor ctermbg=15 guibg=#ffffff ctermfg=0 guifg=#000000
```

**Comment by manasthakur** [comment]
No, it doesn't seem to make any change.
I checked with other colorschemes: default doesn't have this issue. And I found that gruvbox specifically handles this using some method I don't understand: morhetz/gruvbox#2

**Comment by lifepillar** [comment]
Thanks, I'll take a look and report back.

**Comment by lifepillar** [comment]
Could you please try another couple of colorschemes? How do `blue` and `zellner` behave?

**Comment by lifepillar** [comment]
Also, could you try the current master? I have updated the `Cursor` highlight group to use a blue background and white foreground.

**Comment by manasthakur** [comment]
Hi @lifepillar ,

`blue` and `zellner` behave fine (proper cursor colors over search highlights).
Updating to current master didn't help.

One solution can be to supply a value (different from vim background color) for `ctermbg` in `Search` highlight group. However, that solution would lead to a deviation from the existing solarized colors, which some people might not like.

**Comment by lifepillar** [comment]
I think the culprit is `reverse` in the `Search` higroup. How does the cursor look like over search highlights after this command:

```
hi! Search cterm=NONE gui=NONE ctermbg=3 ctermfg=0 guibg=#b58900 guifg=#002b36
```

?

**Comment by manasthakur** [comment]
This solves the issue; however, changes the fg color of text in a searched term from white to black.
I'm okay with this, though; it's better than cursor not being visible.

**Comment by lifepillar** [comment]
I have tried the terminal in Ubuntu 16.10, and what I see is that the cursor's color is given by the reversed highlight group at the cursor's position. Besides, the cursor is blinking. So, it looks just fine.

Could you please provide more details to reproduce your issue, including your system's version and terminal configuration?

**Comment by manasthakur** [comment]
Yeah, a blinking cursor improves the situation.
As the text color at a searched term is same as the background colour, the reversal, without blinking, renders the cursor invisible.

Closing the issue. Thanks.
