### ISSUE TITLE
Background color different in and outside tmux, for 16 colors mode

### ISSUE THREAD

**Issue by goduck777** [lifepillar/vim-solarized8#50]
I am using a terminal that only support 256 colors (gnome-terminal2). I use vim and solarized and it worked well. But when I use them inside tmux, the color are not correct.

Here is the color without tmux
![image](https://user-images.githubusercontent.com/480275/49174871-473f6580-f315-11e8-8173-e64d888c0735.png)
Here is the color with tmux
![image](https://user-images.githubusercontent.com/480275/49174904-5f16e980-f315-11e8-8430-12826202c994.png)
So I added the following in my vim configurations

```
let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"                                                                                                                                                      
let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"                                                                                                                                                      
set t_Co=256                                                                                                                                                                                 
let g:solarized_use16 = 1                                                                                                                                                                   
set background=dark                                                                                                                                                                          
colorscheme solarized8     
```

Now it looks like
![image](https://user-images.githubusercontent.com/480275/49175043-b1580a80-f315-11e8-832f-5b7e7765f7a3.png)
The main complaint I have now is the background color, which is too light and not the same like the case without tmux. The comments are all bold, which is also weird

I think the special characters I put in "&t_8f" can translate the colors from tmux to terminal, but this is for true color. For 16-bit color, is there an alternative for this?

**Comment by lifepillar** [comment]
You shouldn't need anything special in your `vimrc`. I suggest that you check the output of `echo $TERM` inside tmux, and read about `default-terminal` and `terminal-overrides` options in tmux.

I use a 256-color terminal, too (macOS's Terminal.app). My `.tmux.conf` has:

```
set -g  default-terminal             "tmux-256color"
set -ga terminal-overrides           ",xterm-256color:Tc"
```

hence `$TERM` is set to `tmux-256color` (`$TERM` is `xterm-256color` outside tmux). Of course, `tmux-256color` exists in my system (`man tic` should tell you what the search locations are). I use a terminfo file copied from the ncurses project to enable italics. My colors are fine. So, my best guess is that you may need to change/update your terminfo file.

You need to set `t_8b` and `t_8f` only in terminals supporting true colors.

**Comment by goduck777** [comment]
Thanks. I do have the two lines you suggested in my .tmux.conf. But I find that I also need to set
`export TERM=xterm-256color`
outside tmux to make it work. There seems no way to fix that inside tmux.

gnome-terminal2 does not offer a way to set TERM, and the default is xterm. This is the problem.

**Comment by lifepillar** [comment]
I am afraid I can't help then, other than suggesting to build your own terminfo. You may have more luck asking in tmux's or gnome-terminal2's lists.

**Comment by lifepillar** [comment]
I am closing this, as it appears that you have determined that it depends on your terminal's configuration (or lack thereof).
