### ISSUE TITLE
What's the difference between the normal/flat/low/high variants? 

### ISSUE THREAD

**Issue by infokiller** [lifepillar/vim-solarized8#51]
Hi and thanks for this wonderful project!
I tried to explore the different variants by setting `colorscheme` to `solarized8`/`solarized8_flat`/etc, but I don't see differences when I open it side by side in tmux.
So, what are the differences and what am I missing?

Thanks!

**Comment by lifepillar** [comment]
Here's a screenshot:

<img width="1280" alt="screenshot 2018-12-05 at 09 08 38" src="https://user-images.githubusercontent.com/1193314/49499124-8289e900-f86d-11e8-9195-15b64da86dd8.png">

From left to right, you may see `solarized8_high`, `solarized8`, and `solarized8_low` (dark variant above, light variant below). For a screenshot of `solarized8_flat`, see the Readme: the flat variant is similar to the normal variant, but uses different colors for the status line, tab line and vertical separators.

The main difference between high, normal, and low variants is how the Normal highlight group is defined:

- `solarized8_high` (dark): `ctermfg=247 ctermbg=235 guifg=#93a1a1 guibg=#002b36`;
- `solarized8` (dark): `ctermfg=246 ctermbg=235 guifg=#839496 guibg=#002b36`;
- `solarized8_low` (dark): `ctermfg=246 ctermbg=236 guifg=#839496 guibg=#073642`;
- `solarized8_high` (light): `ctermfg=242 ctermbg=230 guifg=#586e75 guibg=#fdf6e3`;
- `solarized8` (light): `ctermfg=66 ctermbg=230 guifg=#657b83 guibg=#fdf6e3`;
- `solarized8_low` (light): `ctermfg=66 ctermbg=254 guifg=#657b83 guibg=#eee8d5`.

Perhaps, your display has low contrast and the differences are not very visible.

**Comment by infokiller** [comment]
Indeed, with changed display settings I can see the differences in your screenshots.
Thanks a lot for the screenshots and explanations, it's really useful!

**Comment by bam80** [comment]
> the flat variant is similar to the normal variant, but uses different colors for the status line, tab line and vertical separators

I think it should be in the Readme.
Also, it would be fine to have all those screenshots there.

**Comment by bam80** [comment]
Also, don't we should make the flat "variant" as an option, so it could be applied to any others "main" variants?

**Comment by lifepillar** [comment]
I have added the screenshot to the Readme.

I have added a `"flat"` value to `g:solarized_statusline`, which you can use in any variant (it does nothing in solarized8_flat, because, well, that's already “flat”). Even with this new option, I retain solarized8_flat because it has several other subtle differences compared to solarized8, not just in the status line, vert bars and tab bar.
