### ISSUE TITLE
Solarized8_flat enabling ligatures on current line

### ISSUE THREAD

**Issue by rktjmp** [lifepillar/vim-solarized8#52]
When using `solarized8_flat` in Neovim, while in `normal` mode, the current line is drawn with ligatures. The behaviour persists in `insert` mode but disappears in `visual` mode.

I'm using iTerm2 3.2.6, my font is Fira code. In iTerm2 Preferences -> Profile -> Text I have `use ligatures` unchecked. Neovim 0.3.1 on OS X 10.13.

`syntax`/`ft` does not effect the behaviour.

I can't see any mention of ligatures in solarized8's code. I can't imagine it being a vim setting since font rendering is a bit out of scope.

I'm *assuming* this probably isn't actually a bug here but maybe in ... iTerm2? This is the only theme I've seen the behaviour in though, and only in the flat variant.

So I guess... Is it intended?

*solarized8_flat*
<img width="303" alt="solarized8_flat_ligature" src="https://user-images.githubusercontent.com/866010/49695254-53b49f80-fbec-11e8-83a1-c2094287d535.png">

*solarized8*
<img width="343" alt="solarized8_no_ligature" src="https://user-images.githubusercontent.com/866010/49695252-51524580-fbec-11e8-9a0b-6edaa211cebc.png">

**Comment by lifepillar** [comment]
No, it’s not intended and I doubt that the colorscheme is to blame. I will try to reproduce it.

**Comment by rktjmp** [comment]
I've noticed it seems to be kind of sporadic. At any rate, like you say it's not intended and I really doubt it's actually a bug with solarized8 so I'm going to close this out.

**Comment by lifepillar** [comment]
I can reproduce it systematically, using Vim and NeoVim. It does not depend on the colorscheme: it happens any time a highlight group has `underline` enabled. It might be worth reporting to iTerm2's author.

**Comment by rktjmp** [comment]
Thanks for doing the reproduction work, I've submitted an [iterm2 issue](https://gitlab.com/gnachman/iterm2/issues/7437). It was appearing sporadically on my system because it only occurs  when "GPU Rendering" is disabled, which only happens when I disconnect my laptop power.
