### ISSUE TITLE
Install using NeoBundle

### ISSUE THREAD

**Issue by Franchium** [lifepillar/vim-solarized8#53]
How to install this plugin using NeoBundle?

**Comment by Franchium** [comment]
I already install it, but i need to change my term variable to 256-color and set termguicolor to active the solarized. It did work but when iam moving the cursor to the top or bottom there is a dark background instead of solarized color.

**Comment by Franchium** [comment]
If iam using xterm-16color or xterm, i got not enough color msg

**Comment by lifepillar** [comment]
Which terminal? Which Vim version? Which OS?

**Comment by Franchium** [comment]
Terminal = xterm
Vim version = 8
OS = blackarch

**Comment by lifepillar** [comment]
>when iam moving the cursor to the top or bottom there is a dark background instead of solarized color.

Is that similar to issue https://github.com/lifepillar/vim-solarized8/issues/54?

>If iam using xterm-16color or xterm, i got not enough color msg

Solarized8 needs a terminal supporting at least 16 colors.

**Comment by lifepillar** [comment]
>Solarized8 needs a terminal supporting at least 16 colors.

This is no longer true. The current master gracefully degrades to  8 colors and black&white terminals.

**Comment by lifepillar** [comment]
I assume that you have determined that this is a terminal/Vim issue, so I am closing this. Feel free to reopen if you think that this depends on a Solarized 8's bug.
