### ISSUE TITLE
Backgroud color not correct for the lines selected

### ISSUE THREAD

**Issue by colinhd8** [lifepillar/vim-solarized8#54]
The background color not changed for the selected lines. for example:
![vim](https://user-images.githubusercontent.com/5259758/52628789-52a53480-2ef3-11e9-82b8-f6ee5b968ac9.jpg)
all lines were selected, but the background is strange.
os: ubuntu 18.04
terminal: mobaxterm 11.0
vim:8.0.1453
vimrc: see the example picture

**Comment by lifepillar** [comment]
I suspect that it is a terminal-specific issue. Can you reproduce it with a different terminal? Can you reproduce it in the same terminal with a different colorscheme?

**Comment by lifepillar** [comment]
Also, does that terminal support true colors? There might be issues with your version of Vim when `termguicolors` is set. I can't recall the details, but, for instance, see [this patch]( https://github.com/adizero/vim/commit/a1cc6baf4de4198d16390ef03084aa512f614ec4).

If `termiguicolors`is set, what happens if you unset it?

**Comment by colinhd8** [comment]
Yes, the terminal support true colors. 
I try again with a different terminal(GNOME Terminal 3.28.2), and found that it's ok.
So maybe it's a terminal-specific issue.

If unset termiguicolors, the selection workd, but the color is not expected.
And i also try a different colorscheme(solarized8, solarized8_low, solarized8_flat), they are same with solarized8_high.

**Comment by lifepillar** [comment]
Unfortunately, I don’t think that much can be done to fix it, other than updating Vim or switching terminal. Anyway, I’ll leave this open. Perhaps, someone will come with a workaround.

**Comment by colinhd8** [comment]
OK，thanks any way.

**Comment by lifepillar** [comment]
One thing you may try is `let g:solarized_termtrans = 1` to set a transparent background.

**Edit:** fix typo.

**Comment by colinhd8** [comment]
The result is:
![vim](https://user-images.githubusercontent.com/5259758/52896527-6824a200-3204-11e9-9873-e5195d6285ad.PNG)
pay attention to the line 22(current line), seems that it's not work for the current line.

**Comment by lifepillar** [comment]
Perhaps, it’s worth asking mobaxterm’s devs.

**Comment by lifepillar** [comment]
I assume that you determined that this was a terminal issue. Feel free to reopen if you think that this is a Solarized 8's bug.
