### ISSUE TITLE
open xfce4-terminal display a lot of `Ptmux;` when I add bash "solarized8.sh" to my zshrc

### ISSUE THREAD

**Issue by fcying** [lifepillar/vim-solarized8#56]
![image](https://user-images.githubusercontent.com/106934/53473461-66c96400-3aa5-11e9-9faa-50b2729303ae.png)

In tmux, it work fine.

**Comment by fcying** [comment]
I use vnc connect the os, $TMUX always has value, without vnc it work fine
```
use vnc:
echo $TMUX
/tmp/tmux-1000/default,44560,0

without vnc:
echo $TMUX
```

**Comment by lifepillar** [comment]
I have copied that script from some other project (I don't remember which—base16, perhaps), and didn't give it much testing. If you have suggestions for improving it, please consider submitting a pull request!
