### ISSUE TITLE
How to change the color of search hits

### ISSUE THREAD

**Issue by serend1p1ty** [lifepillar/vim-solarized8#58]
Hi, @lifepillar , I am sorry to disturb you.
Default color of search hits is a little dazzling, so I want to change it.
I found a solution in stackoverflow: `hi Search cterm=NONE ctermfg=grey ctermbg=blue`
But it seems to does not work.
Can you help me? I will be very grateful.

**Comment by lifepillar** [comment]
If you are using a terminal that supports true colors, you must set `guifg` and `guibg` as well. This works for me (in my vimrc):

```vim
colorscheme solarized8
hi Search cterm=NONE ctermfg=grey ctermbg=blue gui=NONE guifg=#dddddd guibg=#0000ff
```

**Comment by bam80** [comment]
Hmm.. Does it mean the scheme needs some tweaking still?

**Comment by lifepillar** [comment]
I’m afraid I don’t understand your question. Do you want to override `Search` syntax highlighting in your own configuration (which is what my reply above assumes), or are you proposing to change how `Search` is defined in the colorscheme?

**Comment by bam80** [comment]
To be honest I didn't see the issue itself yet.
But if many people want it, doesn't it mean the scheme needs some refinement maybe?
Just asking

**Comment by lifepillar** [comment]
Changing the defaults of the current colorscheme would surely upset some users. But one may change the behaviour based on some setting. I'd prefer not to add new options: how about reusing `g:solarized_visibility` for this? For instance, `let g:solarized_visibilty = 'low'` might also affect `Search` and `IncSearch`. But the colors must be from the Solarized palette: for dark Solarized, we might go with a grayish (`#586e75`) background 

```vim
hi Search cterm=reverse ctermfg=3 gui=reverse guifg=#586e75
```

If you want a blue background, the color code is `#268bd2` (perhaps, too bright?). For the available colors, see `templates/solarized8.colortemplate`. If you propose one or two combinations that you like—and I don't dislike :)— I will add them to the colorscheme. Even better if they look good in all variants of Solarized 8!

**Comment by bam80** [comment]
Maybe @ppnman would express his opinion on this matter?
I didn't start using the scheme yet(just found it yesterday) so I can't say)
PS:
but overall the idea looks good

**Comment by serend1p1ty** [comment]
Thanks for your answer, all I want to do just is
```
hi Search cterm=NONE ctermfg=yellow ctermbg=NONE gui=NONE guifg=#FFFF00 guibg=NONE
hi IncSearch cterm=NONE ctermfg=yellow ctermbg=NONE gui=NONE guifg=#FFFF00 guibg=NONE

```
The solution by @lifepillar is best fit for me!
