### ISSUE TITLE
vimdiff is mostly grey (terminal, set notermguicolors)

### ISSUE THREAD

**Issue by vdrandom** [lifepillar/vim-solarized8#6]
I've recently switched to using solarized8_light instead of solarized and have noticed a bit of an issue with how vimdiff looks. The highlighted areas are grey in the terminal (set termguicolors does not have this issue). It's most likely due to the fact that solarized terminal theme uses bold colours as shades of grey instead of brighter colours.

Using urxvt +is fixes the problem, but vte-based terminals (which are more common) behave exactly that way. I understand that the default behaviour in the GUI involves bold and italic fonts in diff mode, but I think keeping colours is more important in this case.

Also, solarized_diffmode = 'low' is not a solution since it also disables the background highlight on areas that are different.

**Comment by lifepillar** [comment]
Are your terminal colors set to the Solarized palette? That is required when you have `notermguicolors`.

**Comment by vdrandom** [comment]
Of course, otherwise I'd get them coloured instead of grey.

**Comment by lifepillar** [comment]
I cannot reproduce the problem. Could you please post a screenshot?

**Comment by lifepillar** [comment]
Now this should work as in the original Solarized. Feel free to reopen this if necessary.
