### ISSUE TITLE
solarized8_flat: “flat” variant. What is this?

### ISSUE THREAD

**Issue by bam80** [lifepillar/vim-solarized8#60]
It's not clear from the Readme what is that `solarized8_flat`?
https://github.com/lifepillar/vim-solarized8#installation

**Comment by lifepillar** [comment]
It's the one shown in the screenshots. The main difference is how the status line, split bars and tab bar look like:

**Solarized 8 (dark):**
<img width="661" alt="screenshot 2019-03-08 at 08 38 31" src="https://user-images.githubusercontent.com/1193314/54014706-dd3d2480-417d-11e9-8190-3f29479e6860.png">

**Solarized 8 Flat (dark):**
<img width="661" alt="screenshot 2019-03-08 at 08 38 42" src="https://user-images.githubusercontent.com/1193314/54014724-e4643280-417d-11e9-9b39-f1de3fbd7587.png">

**Comment by bam80** [comment]
Yep, already found it in neighbor issue.
How about to update the information in Readme?

**Comment by bam80** [comment]
Those two screenshots, maybe include them in the Readme also, sidy-by-side?
It's not too easy to notice the difference when you have to remember the "normal" screenshots below and then scroll to the top to see Flat variant. Don't you think so?

**Comment by lifepillar** [comment]
Ok, the screenshots in the Readme have been updated.

**Comment by bam80** [comment]
Now we can decipher it :-D
Thanks!
