### ISSUE TITLE
Nvim floating window wrong highlighting

### ISSUE THREAD

**Issue by thekaganugur** [lifepillar/vim-solarized8#61]
I will first show the problem with a screenshot:
![shadow](https://user-images.githubusercontent.com/28161197/54815271-a2b9a880-4ca2-11e9-9557-d11101996a03.png)

I tried all solarized themes and you can see the problem. It uses highlight color to draw background instead of highlighting text and drawing the text itself. I tried **gruvbox** and there were  no problems.

Terminal: st (I have the same problem with lxterminal too)
No tmux.

**Comment by lifepillar** [comment]
Thanks for reporting. Can you please provide some details about how to get such highlighted entries? Like, NeoVim version, plugin used, filetype…, so that I can try reproducing the issue.

**Comment by thekaganugur** [comment]
@lifepillar 
- NVIM version: NVIM v0.4.0-430-g8698830cb
- How to get floating window: You cant in stable version but you can try nightlies (v0.4.0-430-g8698830cb works for me), combined with. [coc](https://github.com/neoclide/coc.nvim)
- Coc provides LSP and completion. (**:CocInstall coc-tsserver** for JS and TS files, floating windows work out of box)
- Plugins I'm using related to syntax higlighting: 'tpope/vim-markdown', 'chemzqm/vim-jsx-improve' 'HerringtonDarkholme/yats.vim'

I had to switch vim-one since I can't find a working solarized theme for this situation. (See example below)
![image](https://user-images.githubusercontent.com/28161197/54868231-6158f400-4d9b-11e9-8710-eaeb8bdd8727.png)
Foreground and background settings are reversed somehow with solarized.
Thank you

**Comment by lifepillar** [comment]
Please also provide the text to type to get a floating window to open. I have installed the latest NeoVim and coc.nvim, but I still see normal pop-up menus.

**Comment by thekaganugur** [comment]
Sorry,
- I can get floating window with these minimal vimrc: (with nightly version: NVIM v0.4.0-430-g8698830cb)

```
call plug#begin('~/.nvim/plugged')
Plug 'lifepillar/vim-solarized8'
Plug 'tpope/vim-markdown'
Plug 'chemzqm/vim-jsx-improve'
Plug 'HerringtonDarkholme/yats.vim'
Plug 'neoclide/coc.nvim', {'tag': '*', 'do': { -> coc#util#install()}}
call plug#end()

filetype plugin indent on
syntax on
let g:markdown_fenced_languages = ['css', 'javascript', 'js=javascript', 'typescript']
set termguicolors
colorscheme solarized8_flat
```
- According to [Coc installation page](https://github.com/neoclide/coc.nvim/wiki/Install-coc.nvim)
    - nodejs: `curl -sL install-node.now.sh | sh`
    - yarn: `curl --compressed -o- -L https://yarnpkg.com/install.sh | bash`
is needed.

-  Install tsserver with `:CocInstall coc-tsserver` > Open an `example.js `file and write` console.log(` you will see the floating window hopefully.
![shadow](https://user-images.githubusercontent.com/28161197/54879258-fadddf80-4e47-11e9-8301-d790bdf5ea86.png)
Thank you.

**Comment by lifepillar** [comment]
Thanks for all the feedback! Now I can reproduce it and I have nailed the issue.

The problem is that Solarized 8 defines `Pmenu` using `reverse` (try `:hi Pmenu gui=NONE`). Gruvbox does not use `reverse`, so it does not have this issue.

I should be able to fix that soon.

**Comment by thekaganugur** [comment]
Yes, `hi Pmenu gui=NONE` fixes the problem.
Thank you for your time @lifepillar .

**Comment by lifepillar** [comment]
Can you try the current master? Among other things, I have updated the colors for the pop-up menus.

**Comment by thekaganugur** [comment]
Yes it is fixed, thank you for the fix and your time, I'm closing the issue now.
