### ISSUE TITLE
Error highlighting has no background

### ISSUE THREAD

**Issue by fladd** [lifepillar/vim-solarized8#63]
Often (e.g. for Python) Error is used to indicate whitespace mistakes (e.g. too much whitespace). Since in solarized8 Error does not have any background colour, these errors are not visible.

**Comment by lifepillar** [comment]
Thanks for reporting it! I think that the current colors are inherited from Solarized, but you are correct to point out that they should be reversed. I will fix it.

**Comment by bam80** [comment]
Should we push it to upstream?

**Comment by fladd** [comment]
Great, thanks!

**Comment by lifepillar** [comment]
@bam80 If you mean to Solarized's repo, you may try, but AFAIK that colorscheme has not been maintained for a long time.

**Comment by lifepillar** [comment]
Please try the current master and feel free to reopen if the issue is not solved.
