### ISSUE TITLE
Wrong background color with nvim

### ISSUE THREAD

**Issue by thmxv** [lifepillar/vim-solarized8#66]
I am using Git Bash (mintty/MinGW64 version 2.9.4) on windows 10 with the following .vimrc:
```
" Modern vim
set nocompatible

" Pathogen plugins and scripts manager
" Install plugins/scrypts by copying into in ~/.vim/bundle/
execute pathogen#infect()

" Theme
set termguicolors
set background=dark
colorscheme solarized8
" Statusbar theme
let g:airline_theme='solarized'
let g:airline_solarized_bg='dark'

" 80 columns limits
set colorcolumn=80
" Display line numbers
set number
" Mode already in statusbar
set noshowmode
```

Although everything works well with vim, the background color is wrong with nvim 0.3.5.
nvim:
![nvim_background](https://user-images.githubusercontent.com/948798/58440433-6ba3b100-80b0-11e9-9d4f-e96d7c8810cc.png)
vim:
![vim_background](https://user-images.githubusercontent.com/948798/58440481-ae658900-80b0-11e9-96c2-cb0933326970.png)

**Comment by thmxv** [comment]
I think I found the culprit: NeoVim does not work with mintty so I had a alias in my bashrc that was always running nvim trough winpty to workaround the issue, but winpty does not support true colors.

**Comment by lifepillar** [comment]
So, if you `set notermguicolors`, you get the right colors (256-color approximation, see Readme)?

**Comment by thmxv** [comment]
With winpty and notermguicolors I do not get the right colors and neither do I get the approximation (the one that looks like a different colorscheme). I get something with lot of unreadable text having the same color  has the background (see picture) and the following error message when starting up (only with vim, nvim stays silent):

```
Error detected while processing /c/Users/xavie/.vim/bundle/vim-solarized8/colors/solarized8.vim:
line   11:
[Solarized 8] There are not enough colors.
```
It was my understanding the approximation is for 256 colors but winpty does not even support that.

 Moreover, but unrelated to this project, the solarized airline theme does not behave with notermguicolors.

![nvim_notermguicolors](https://user-images.githubusercontent.com/948798/58488902-99d0d180-8140-11e9-8950-1be10ee81185.png)

**Comment by thmxv** [comment]
Just to be clear: I think you can close this issue as it relates more to winpty than here.
Personally I will stick with vim and avoid winpty when I can.

**Comment by lifepillar** [comment]
>[Solarized 8] There are not enough colors.

Check `:set t_Co`. i guess that the value is less than 256. What happens if you set `t_Co` to 256 in your `vimrc`?

I'll leave this open for now: I plan to release a new version of Solarized 8 that does not produce the error above.

**Comment by thmxv** [comment]
With t_Co set to 256 I do not have any error message but wrong colors, not the approximated one. To recap this is with the winpty wrapper, without it all is good (except that nvim does not work in mintty)

**Comment by lifepillar** [comment]
So, I am closing this as it does not seem to be a color scheme issue.
