### ISSUE TITLE
 now vim(not only vimr) users must set termguicolors before loading the color scheme

### ISSUE THREAD

**Issue by X1aomu** [lifepillar/vim-solarized8#68]
I am a vim(8.1.1467) user. I got the same problem with recently change as described in #67.
I haven't know the reason about this. Is it suggest it's a more common case not only limited to vimr?

**Comment by lifepillar** [comment]
The update might just expose a wrong configuration. Or maybe there’s really a bug in the color scheme. Can you provide some details about your setup?

**Comment by X1aomu** [comment]
Before (causes problem with recently updates):

```
" color scheme
set background=light
let g:solarized_term_italics = 1 " must set this before setting colorscheme
let g:solarized_extra_hi_groups = 1
colorscheme solarized8
let g:airline_theme = 'solarized'

" Enable true color
if exists('+termguicolors')
  set termguicolors
  let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
  let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
endif
```

Now:

```
" Enable true color
if exists('+termguicolors')
  set termguicolors
  let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
  let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
endif

" color scheme
set background=light
let g:solarized_term_italics = 1 " must set this before setting colorscheme
let g:solarized_extra_hi_groups = 1
colorscheme solarized8
let g:airline_theme = 'solarized'
```

I'll be appreciated if you can help me find my wrong configuration.

**Comment by X1aomu** [comment]
Umm... I found something really strange.
The problem disappear after I delete the line `let g:solarized_extra_hi_groups = 1` and restart vim and then add that line back and restart vim again. (Because it's the line I added recently, I want to check if it matters.)

Now no matter what I do in my vimrc (change the order of setting color scheme and setting termguicolors or add/delete `let g:solarized_extra_hi_groups = 1`), I cannot reproduce the problem.

It's just last night that the order of setting colorscheme and termguicolors made things different.

**Comment by lifepillar** [comment]
Ok, good. You may remove this line:

```vim
let g:solarized_term_italics = 1 
```

because that option has been removed: Solarized 8 now detects automatically whether italics is supported.

The fact that the issue has disappeared after removing `g:solarized_extra_hi_groups` makes me wonder: do you often switch between different color schemes? Because, as noted in the Readme and in the help file, turning on that setting may compromise highlighting when you change color scheme.

**Comment by X1aomu** [comment]
@lifepillar Thanks for your reminder of that. I don't often change my color scheme. I've used this color scheme for some time and I haven't tried another recently.
