### ISSUE TITLE
[question] Should Error and Todo highlight group has same background color?

### ISSUE THREAD

**Issue by StarryLeo** [lifepillar/vim-solarized8#69]
I found error sign and warning sign has different background color when I using [ALE](https://github.com/w0rp/ale). I found ALE link the highlight to highlight group Error and Todo by default: https://github.com/w0rp/ale/blob/507f164a09d2cb3c99983424f9d186d6f4081820/autoload/ale/sign.vim#L24
Many plugins do the same,  Although it seems that there is no standard. And I found the color scheme has duplicate places, this is, the highlight group ErrorMsg and Error do almost the same thing, only the difference in bold. I don't understand very well, is there any special purpose?

![snipaste20190609_161251](https://user-images.githubusercontent.com/25200758/59156680-de118980-8ad1-11e9-8b32-7f3d6707835d.png)

![snipaste20190609_161507](https://user-images.githubusercontent.com/25200758/59156691-0f8a5500-8ad2-11e9-847d-5069ea5ed31c.png)

**Comment by StarryLeo** [comment]
Especially some plugins with syntax checking, such as
[syntastic](https://github.com/vim-syntastic/syntastic): 

https://github.com/vim-syntastic/syntastic/blob/11aa21edef1627139d1cb39f5efd568942985dfc/plugin/syntastic/signs.vim#L55
 
[YouCompleteMe](https://github.com/Valloric/YouCompleteMe):

https://github.com/Valloric/YouCompleteMe/blob/59eea79da8acaf4cd01631b15d6c762f9b9bdb14/autoload/youcompleteme.vim#L343

they set the default like ALE.

**Comment by lifepillar** [comment]
To answer the question in the subject: no, `Error` and `Todo` do not need to have the same highlighting (if they did, we could go with just one highlight group, right?). They have different purposes (highlighting errors vs drawing attention on some paragraph), hence they typically adopt different highlighting (`Error` being visually more prominent than `Todo`).

Regarding ALE highlighting and how to change it, see https://github.com/lifepillar/vim-solarized8/issues/64. ALE obviously provides defaults, but one cannot expect that they blend well with every color scheme out there and that they fit everyone's taste. So, it also provides custom highlight groups (such as `AleErrorSign`), which you may easily re-link to suit your needs.

>And I found the color scheme has duplicate places, this is, the highlight group ErrorMsg and Error

According to `:help hl-ErrorMsg`, `ErrorMsg` is (mostly) for highlighting error messages on the command line. `Error` (see `:help group-name`) is typically used for syntax items (e.g., erroneous constructs in your source code). All this is just convention of course, and the highlighting of such groups may concide or not: it depends on the color scheme.

>I don't understand very well, is there any special purpose?

I think Vim's documentation summarises it well (`:help group-name`):

>To be able to allow each user to pick his favorite set of colors, there must be preferred names for highlight groups that are common for many languages.

So, there should be a sufficiently large number of highlight groups to allow flexible customization.

**Comment by StarryLeo** [comment]
Thanks for your detailed answer, it solved my question perfectly!
