### ISSUE TITLE
Terminal cursor should be visible for focused and non-focussed :terminal buffers

### ISSUE THREAD

**Issue by nelstrom** [lifepillar/vim-solarized8#7]
This issue only applies to [NeoVim](https://github.com/neovim/neovim)'s terminal emulator buffers.

When in terminal mode, the terminal cursor is easily visible, which is good. But on exiting terminal mode, the terminal cursor disappears, which makes it difficult to tell where the terminal cursor will be when terminal mode resumes.

This could be addressed by defining colors for the [TermCursorNC](https://neovim.io/doc/user/syntax.html#hl-TermCursorNC) group.

**Comment by lifepillar** [comment]
Thanks, that looks like a good idea. Which terminal can I use to reproduce this?

**Comment by lifepillar** [comment]
Never mind, I've reproduced it in macOS's Terminal.app. I'll merge https://github.com/lifepillar/vim-solarized8/issues/8 (please review my comment there).
