### ISSUE TITLE
wrong colors with latest version

### ISSUE THREAD

**Issue by frediana** [lifepillar/vim-solarized8#70]
Hi there,

I go wrong colors when updating to latest version.

I had to return to this commit: 30fd919 to get everything work as previously.

Not sure if I need to change something to my conf to get it working or if this is a regression in the plugin? Maybe you can give me a tip, here is my config:

Mac Os: 10.14.5
iterm2: Build 3.2.9
NVIM v0.3.1

vim config:
```
colorscheme solarized8_flat
set background=dark
if has("termguicolors")
   set termguicolors
endif
```

Version OK (Before update):
<img width="1436" alt="Screenshot 2019-06-16 at 10 04 37" src="https://user-images.githubusercontent.com/903834/59561247-4c989f00-901e-11e9-80dc-e8d26edc059e.png">

Version Broken (since last update):
<img width="1438" alt="Screenshot 2019-06-16 at 10 04 05" src="https://user-images.githubusercontent.com/903834/59561243-3e4a8300-901e-11e9-9f85-bc576b3e1707.png">

Let me know if you need more information...

Thanks,

Adrien

**Comment by lifepillar** [comment]
Set `termguicolors` before loading the color scheme. Does it fix it?

**Edit:** fix typo.

**Comment by lifepillar** [comment]
Also the background should be set before loading the color scheme.

**Comment by frediana** [comment]
Thank you it now working fine with the config in this order:

```
if has("termguicolors")
  set termguicolors
endif
set background=dark
colorscheme solarized8_flat
```
