### ISSUE TITLE
strange error when loading nvim 

### ISSUE THREAD

**Issue by brettswift** [lifepillar/vim-solarized8#73]
I've tried to isolate this but haven't had much luck. 

This could be an issue with this plugin only if it exists with something else I have configured.   
However I only see this error when this plugin is enabled. 

I get this when I load nvim: 
```
Error detected while processing function <SNR>49_AddAnsiGroups:
line   18:
E730: using List as a String
```

When I swap this out for the dracula theme I don't get that error. 

https://githiub.com/brettswift/linux-dotfiles/blob/cc6f13ea739387a73ee897e3d5db8031c6ce6206/.config/nvim/general.vim#L69

My dotfiles are public and the link above is where the theme is set.  

I'm still getting used to nvim and vim-plug.  If there's a debug command I can run that would help, I'd be happy to. 

Any idea what the issue is?

**Comment by lifepillar** [comment]
I’ll take a look at your vimrc, but `AddAnsiGroups()` is not a function defined by Solarized 8.

**Comment by brettswift** [comment]
Thanks.   I didn't see that function in your code, so was guessing it was a dependency, or that the function might be familiar to you. 

I'll close the issue.  If you do have a chance to look at my configs and notice anything obvious, I'd appreciate it!

**Comment by lifepillar** [comment]
The culprit is coc.nvim: https://github.com/neoclide/coc.nvim/blob/4fe01e0597e4b4a52a3216c7a363fa5396d5e217/plugin/coc.vim#L86

There is a bug at line https://github.com/neoclide/coc.nvim/blob/4fe01e0597e4b4a52a3216c7a363fa5396d5e217/plugin/coc.vim#L93. Instead of

```vim
let color_map[name] = get(g:, 'terminal_ansi_colors', i)
```

that line should read something like:

```vim
let color_map[name] = get(g:terminal_ansi_colors, i, 'SOME DEFAULT HERE')
```

The reason why you hit that bug with Solarized 8 is that Solarized 8 always defines `g:terminal_ansi_colors`, even in Neovim. IMO, they should change the conditional from

```vim
    if exists('g:terminal_ansi_colors')
      let color_map[name] = get(g:, 'terminal_ansi_colors', i)
    else
      let color_map[name] = get(g:, 'terminal_color_'.i, colors[i])
    endif
```

to

```vim
if has('nvim')
   let color_map[name] = get(g:, 'terminal_color_'.i, colors[i])
elseif exists('g:terminal_ansi_colors')
  let color_map[name] = get(g:terminal_ansi_colors, i, 'SOME DEFAULT HERE')
else
  " Raise an error? Fallback to some defaults?
endif

**Comment by brettswift** [comment]
:+1:   That's awesome.   Thanks for your help!
