### ISSUE TITLE
Space in 'go' file causes red background

### ISSUE THREAD

**Issue by thekaganugur** [lifepillar/vim-solarized8#74]
![image](https://user-images.githubusercontent.com/28161197/63231708-6d50c100-c228-11e9-8592-894564994b2e.png)
You can see the problem in picture, it's produced with space + enter + space
Then if i type a character this is what happens:
![image](https://user-images.githubusercontent.com/28161197/63231727-a9842180-c228-11e9-8561-6b6495bcb3d7.png)

I'm using this theme for a long time, it happened only in 'go' files so far.

**Comment by lifepillar** [comment]
Likely a “feature” of your Go plugin. Have you checked whether there’s an option to hide/show trailing spaces?

**Comment by thekaganugur** [comment]
Yes, my bad.
For reference to other people: `let g:go_highlight_trailing_whitespace_error = 0` fixes the problem.
Closing the issue.
