### ISSUE TITLE
Suggest for Vim inclusion?

### ISSUE THREAD

**Issue by fladd** [lifepillar/vim-solarized8#75]
Hi there,

I think Solarized 8 is well suited for inclusion in Vim, since it is a more lightweight version of the rather popular original Solarized.

See here for more details: https://github.com/vim/vim/issues/4996

**Comment by lifepillar** [comment]
Thanks for heads up. I am aware of that discussion, but I am waiting to see how it develops. Yes, Solarized 8 simplifies Solarized, but it's still a pretty complex color scheme. I think Vim developers are looking for something easier to maintain and possibly not so popular, as popular color schemes tend to attract lots of issues :)

**Comment by fladd** [comment]
Maybe, but while it is not perfect, it is the most complete colorscheme with the least issues. I tried pretty much everything that is out there, and I keep coming back to Solarized 8.
Another option for Vim could be to make the default theme for light backgrounds (which is actually quite functional), also work for dark backgrounds.

**Comment by lifepillar** [comment]
Thanks for the feedback. I'll leave this open for now, and wait to see what direction https://github.com/vim/vim/issues/4996 takes.

**Comment by lifepillar** [comment]
Closing this, as there is now [vim-colorschemes](https://github.com/vim/colorschemes/) to coordinate the efforts to embed new colorschemes into Vim.

This colorscheme does not satisfy the requirements for inclusion there, but could be used as a blueprint for a version suitable for inclusion, if anyone cares to work on that.
