### ISSUE TITLE
base0 or base1 for normal text

### ISSUE THREAD

**Issue by simplelife2010** [lifepillar/vim-solarized8#78]
I like this setup.
Why do you use base1 for normal text instead of base0 like in the original?

**Comment by lifepillar** [comment]
For increased contrast and to differentiate the Solarized variants more. The Solarized palette does not have much contrast in general and, although the contrast between the background and base0 is acceptable, I found base1 more pleasant to my eyes. The `solarized8_flat` variant uses base0.

If you prefer less contrast, you may use `solarized8_flat` or `solarized8_low`, or change a line in the template and rebuild it with [Colortemplate](https://github.com/lifepillar/vim-colortemplate).

**Comment by simplelife2010** [comment]
I understand, thank you very much.
