### ISSUE TITLE
"Super light" version

### ISSUE THREAD

**Issue by kristijanhusak** [lifepillar/vim-solarized8#79]
Hello,

would you consider adding a version of light colorscheme that's even lighter than flat version?
For example normal background to be something like in [onehalf](https://github.com/sonph/onehalf/tree/master/vim), almost completely white (#FAFAFA to be precise).

Onehalf is nice, but solarized distinguishes certain parts of code better. Flat version of solarized is still a bit too yellow for me.

I can create a PR with an example how i think it should look like.

**Comment by lifepillar** [comment]
I consider the Solarized palette cast in stone. Besides, this color scheme is already way too complex. I think you'd be better off forking this project, hacking it (with Colortemplate it's very easy) and build your own color schemes. After you have changed the background, you'll likely want to adjust the other colors as well ;-)

**Comment by kristijanhusak** [comment]
Yeah few colors needs tweaking, but it looks fairly ok. I'll make it in a fork and we will see if it fits or not. Thanks.
