### ISSUE TITLE
Why is there a pause when launching vim

### ISSUE THREAD

**Issue by CMCDragonkai** [lifepillar/vim-solarized8#81]
I find that when running vim with this scheme, there's always a pause and I have to hit any character to enter the display. This didn't happen with the older colour scheme.

I'm running vim 8 in powershell in conemu FYI.

**Comment by lifepillar** [comment]
Try `vim --startuptime time.txt`, then open `time.txt` and search for `solarized8`. Please report the time on the second column. Please also report the output of:

```
:set t_Co
:set termguicolors
```

**Comment by CMCDragonkai** [comment]
It's not that it takes long to startup, it's that there's a blank startup screen, and it asks me to enter some key to continue.

**Comment by lifepillar** [comment]
Ops, sorry, read too fast. Does `:messages` provide any clue? I have no idea why a colorscheme would cause Vim to prompt for a key. Does it happen with a minimal `vimrc` that only sets the colorscheme?

**Comment by CMCDragonkai** [comment]
This is what it looks like:

![GIF 22-03-2020 7-51-09 PM](https://user-images.githubusercontent.com/640797/77245950-dd1fa200-6c76-11ea-8b1b-1a876657c56e.gif)

**Comment by CMCDragonkai** [comment]
The `:set t_Co` says 16. If I use `:set termguicolors`, it changes the colors entirely and looks weird.

Oh I see something strange with `:messages`:

```
E185: Cannot find color scheme 'solarized'
```

**Comment by CMCDragonkai** [comment]
This is pretty strange, as I have vim-solarized8 cloned to:

```
C:\Users\CMCDragonkai\vimfiles\pack\plugins\start\vim-solarized8
```

And this is where it is intended to put vim plugins in 8+ and they are meant to be autoloaded. None of the other plugins are missing, I have other plugins.

**Comment by CMCDragonkai** [comment]
Ok I've solved the pause problem. Sorry, I had just transitioned from the old vim solarized theme and thought that the colour scheme would be the same.
