### ISSUE TITLE
Setting termguicolors makes the text in the cursorline the same grey color, removing it solves the problem

### ISSUE THREAD

**Issue by CMCDragonkai** [lifepillar/vim-solarized8#82]
However without termguicolors, it looks like the solarized colors is not correct. Compare the 2:

![image](https://user-images.githubusercontent.com/640797/77246534-6b4a5700-6c7c-11ea-81ce-b95654b9775d.png)

![image](https://user-images.githubusercontent.com/640797/77246537-77361900-6c7c-11ea-8e6e-a1d4a2225fdd.png)

**Comment by lifepillar** [comment]
That is how it is supposed to look. Compare with the screenshots in the README.

The colors of the Solarized palette, or even somewhat similar colors, are not available in xterm. What you see there in your first screenshot is the best possible approximation. A couple of workarounds are suggested in the README: the easiest is probably to change your terminal's 16 colors to Solarized colors, and then `set t_Co=16`.

If your terminal *does* support millions of colors, though, just `set termguicolors` in your vimrc and you are done.

**Comment by lifepillar** [comment]
Sorry, I hadn't realized that this was about the cursor line. Please provide the output of:

```
:hi Normal
:hi CursorLine
```

when `termguicolors` is set. The two highlight groups should use different colors. If they do, but you still don't see the cursor line, that is likely an issue with your terminal, e.g., some terminals provide a way to tweak the contrast, which may help.

**Comment by lifepillar** [comment]
Closing for lack of feedback, and also because I could not reproduce the issue.
