### ISSUE TITLE
Support for treesitter?

### ISSUE THREAD

**Issue by tkolleh** [lifepillar/vim-solarized8#83]
Does vim-solarized8 support [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter) plugin? There seems to be issues with highlight groups.

<img width="528" alt="Screen Shot 2020-08-24 at 12 54 51 AM" src="https://user-images.githubusercontent.com/3095197/91005266-71828d80-e5a4-11ea-9c58-1ae8c0b1d39e.png">

**Comment by lifepillar** [comment]
Not that I know of. A pull request is welcome, or at least a specification of what highlight groups to add, with what colors.

**Comment by tkolleh** [comment]
First attempt at updating `solarized8_high.vim` with nvim-treesitter highlight groups. I haven't settled on any colors yet, just trying to understand how this would be supported.

Highlight groups are from [this point](https://github.com/nvim-treesitter/nvim-treesitter/blob/6f1908a2ecd61071af9203b8d058ce189476b38c/doc/nvim-treesitter.txt#L540) in the treesitter docs.

The below edit was made in `plugged/vim-solarized8/colors/solarized8_high.vim`. What is the recommended way to quickly test color assignments after linking groups?

```vim
" nvim-treesitter/nvim-treesitter {{{
hi!   link   TSPunctDelimiter   Special
hi!   link   TSPunctBracket     Special
hi!   link   TSPunctSpecial     Special
hi!   link   TSConstant         Constant
hi!   link   TSConstBuiltin     Constant
hi!   link   TSConstMacro       Preproc
hi!   link   TSString           Constant
hi!   link   TSStringRegex      Constant
hi!   link   TSStringEscape     Constant
hi!   link   TSCharacter        Special
hi!   link   TSNumber           Constant
hi!   link   TSBoolean          Constant
hi!   link   TSFloat            Constant
hi!   link   TSFunction         Identifier
hi!   link   TSFuncBuiltin      Function
hi!   link   TSFuncMacro        Function
hi!   link   TSParameter        Delimiter
hi!   link   TSMethod           Constant
hi!   link   TSField            Constant
hi!   link   TSProperty         Constant
hi!   link   TSConstructor      Constant
hi!   link   TSConditional      Statement
hi!   link   TSRepeat           Constant
hi!   link   TSLabel            Statement
hi!   link   TSOperator         Statement
hi!   link   TSKeyword          Statement
hi!   link   TSException        Statement
hi!   link   TSType             Type
hi!   link   TSTypeBuiltin      Type
hi!   link   TSStructure        Type
hi!   link   TSInclude          PreProc
" }}}

```

**Comment by jandamm** [comment]
They should be supported right out of the box. They are defined inside the tree-sitter plugin:

https://github.com/nvim-treesitter/nvim-treesitter/blob/4a747aa30cc7d1ac73ebe5ac5cee97bf5fccc6d6/plugin/nvim-treesitter.vim

**Comment by tkolleh** [comment]
I am new to color schemes, forgive the basic questions, but its my understanding that those (☝🏾) group links must ultimately link to ( or be assigned to) a color within the active color scheme, i.e.

If `Identifier` below is not aligned with a color in solarized8 or is aligned with the same color as many other groups then there won't be a colored visual distinction for a parameter compared to other structures in the source code. Is that so?

```vim
highlight default link TSParameter Identifier
highlight default link TSParameterReference TSParameter
```

**Comment by jandamm** [comment]
If solarized highlights `Constant` and `Identifier` both blue, than ever `TS` highlight group linking to either will be highlighted blue.

Same is true for most syntax files.
You'll see groups like `{language}Identifier` which links to `Identifier`. So by default it is covered by any theme (unless the theme is incomplete). The theme author can also choose to add more granular support for a language by overwriting those links. This is what you turn on with `g:solarized_extra_hi_groups`.

In your example `TSParameter` and `TSParameterReference` will look exactly the same - like `Identifier`.

**Comment by tkolleh** [comment]
Thanks for the responses. I'll enable extra hi groups. If I have specific changes I'll create a pull request.

**Comment by tkolleh** [comment]
Actually with treesitter its better to keep that off since it provides highlight consistency across file types.

**Comment by jandamm** [comment]
I wasn't suggesting turning it on.
It was just an example where highlight groups beside the defaults(*) are used.

\* `:help group-name`
