### ISSUE TITLE
how to use it？

### ISSUE THREAD

**Issue by jiahe224** [lifepillar/vim-solarized8#87]
I am a Linux beginner and I did the following in the shell.
`git clone https://github.com/lifepillar/vim-solarized8.git ~/.vim/pack/themes/opt/solarized8`
But I don't know where to execute the following command or setting.
`set background=dark`
`colorscheme solarized8`

**Comment by lifepillar** [comment]
To begin with, create `~/.vim/vimrc` with this content:

```vim
set background=dark
colorscheme solarized8
```

Now, when you open Vim, it should use this color scheme by default.

Then, you may want to learn a bit more about Vim. You may type the above commands, and many others, in Vim by typing `:`, which opens Vim's command prompt. The first command you should type is `:help` (followed by Enter).

For a beginner's introduction to Vim, type `vimtutor` in your shell (not inside Vim!), and follow the tutorial.

Good luck!

**Comment by jiahe224** [comment]
Thank you!
