### ISSUE TITLE
Solarized8 background breaks in TMUX 

### ISSUE THREAD

**Issue by asathkum** [lifepillar/vim-solarized8#88]
I'm using PuTTY to ssh into my raspberry pi 4, where running vim inside a tmux 2.8 session breaks my solarized8 background:
![image](https://user-images.githubusercontent.com/28933557/107619282-c758f980-6c07-11eb-829d-bfff8d51dd52.png)

This is what I'm expecting it to look like:
![image](https://user-images.githubusercontent.com/28933557/107619206-aabcc180-6c07-11eb-8788-eaa4ed3dd369.png)

My ``.tmux.conf`` looks like this:
```
set -g  default-terminal            "tmux-256color"
set -ga terminal-overrides          ",xterm-256color:Tc"
```

My ``.vimrc`` looks like this:
```
set background=dark
colorscheme solarized8
set termguicolors
```

I also aliased my ``tmux`` to ``tmux -2`` (which might be redundant) in my ``.bashrc``:
```
alias tmux='tmux -2'
```

I've read several articles discussing this problem (including some closed issues on this repo), but none of the solutions they discussed fixed my background.

**Comment by lifepillar** [comment]
Have you tried the suggestion in the Readme?

If that doesn't work, please provide the output of `echo $TERM` both inside and outside tmux.

**Comment by asathkum** [comment]
> Have you tried the suggestion in the Readme?

Which suggestion specifically?

> If that doesn't work, please provide the output of `echo $TERM` both inside and outside tmux.

I'm getting ``xterm-256color`` in and outside of tmux

**Comment by lifepillar** [comment]
>Try putting this in your `.vimrc`:
>
>    let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
>    let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
>
>See `:h xterm-true-color` for the details.

>I'm getting xterm-256color in and outside of tmux

Given your configuration, I think you should get `tmux-256color` inside tmux. Maybe there is an option in Putty to (not) forward environment variables?

**Comment by asathkum** [comment]
Thanks, I got it to work in and outside tmux on my raspi, but I was having trouble when I ssh'd through PuTTY. 

If anyone else is having the same issue, I was able to resolve it by specifying ``xterm-256color`` in ``Terminal Details`` under ``Connection -> Data``
