### ISSUE TITLE
Improper shebang in solarized8.sh

### ISSUE THREAD

**Issue by hkbakke** [lifepillar/vim-solarized8#89]
The 256 color fix script in `scripts/solarized8.sh` has the shebang `#!/bin/sh`. In many modern distros, e.g. Debian, `/bin/sh` now points to the simpler shell Dash, not Bash. This has some implications as the script uses the double bracket bashism to do the regex match test at line 19.

`if [[ "$TERM" =~ "^(tmux|screen).*" && -n "$TMUX" ]]; then`

Because of the shebang the script execution fails on systems where sh points to other shells. If bashisms are really needed in the code the shebang should probably be changed to 

`#!/usr/bin/env bash`

**Comment by lifepillar** [comment]
If I recall correctly, the script comes from the original Solarized project. Pull requests to make it more widely compatible are welcome!

**Comment by Airwan** [comment]
Hello, by the way, the "set -o errexit" at the very begining of the script cause my terminal to be killed when I mistake.... It should be added at end of the script "set +o errexit" or equivalently "set +e" so that the options do not belong to the session. 
I am not enough specialist to pull request here.
Thanks.

**Comment by hkbakke** [comment]
The base16-shell scripts which this one was based on does not contain "set -o errexit". If the script is run as a command and not sourced it should not be a problem, but as the script is not executable I suspect it is intended to be sourced and then the errexit option should be removed completely to avoid impacting the other stuff that gets loaded by the shell in my opinion.

So either the script is a command and then:
* the shebang should be correct for the functionality used in the script
* the script should be executable

or it is intended to be sourced and then
* the shebang should reflect compatibility, but it could also be ignored
* the script does not need to be executable
* the set -o errexit part should be removed

**Comment by lifepillar** [comment]
I have merged @hkbakke's pull request, which should also address @Airwan's concerns. Please verify and re-open this issue if necessary.
