### ISSUE TITLE
Terminal installation some tricks.

### ISSUE THREAD

**Issue by Airwan** [lifepillar/vim-solarized8#91]
Hello! It is not really an issue just a proposal. To use correctly the scheme for vim through a terminal with 256 colors, two tricks might be mentioned:
1.  The script solarized.sh as you said should be run! not sourced in .bashrc or related. E.g. add `sh /path/to/scripts/solarized8.sh` in your .bashrc. This maid clear the way to "load" the right palette for global used.
2. When using vim plug managers, if someone want to load correctly the scheme at start, a line like `:autocmd vimenter * ++nested colorscheme solarized8_xxx` should be added to the vimrc because just ":colorscheme solarized9_xxx" after the plugin is load may cause strange stuff (at least to me, I have view lines in the default scheme...). The tricks come from Gruvbox wiki. 

Thanks for your work.

**Comment by lifepillar** [comment]
This information has been added to the Readme.
