### ISSUE TITLE
Syntax Highlighting Background Transparency Issue

### ISSUE THREAD

**Issue by ghost** [lifepillar/vim-solarized8#92]
When using the "let g:solarized_extra_hi_groups=1" option in my nvim configuration while also using a transparent terminal, the syntax highlighting does not become transparent like other text. This is pictured below:
![2021_04_23_screenshot](https://user-images.githubusercontent.com/67240033/115827520-62c1d400-a3da-11eb-89d7-3017c5f5ffd1.png)

**Comment by lifepillar** [comment]
Good catch! Fixed in master. Thanks for reporting!

**Comment by ghost** [comment]
Thanks for so quickly fixing this issue! I noticed the same thing in another area, where the "Enter" text on the vim start screen has the same sort of background despite being in a transparent terminal. Pictured below:
![image](https://user-images.githubusercontent.com/67240033/117591409-56d85080-b102-11eb-8139-9e15881a516a.png)

**Comment by lifepillar** [comment]
That seems Neovim-specific. In Vim, the `<Enter>` text has a transparent background:

![transp-intro](https://user-images.githubusercontent.com/1193314/117615000-6b9bff00-b169-11eb-8764-cce0213fd834.jpg)

If that is controlled by a highlight group, I'd be happy to fix it. It may be worth asking Neovim developers.

**Comment by ghost** [comment]
> That seems Neovim-specific. In Vim, the `<Enter>` text has a transparent background:
> 
> ![transp-intro](https://user-images.githubusercontent.com/1193314/117615000-6b9bff00-b169-11eb-8764-cce0213fd834.jpg)
> 
> If that is controlled by a highlight group, I'd be happy to fix it. It may be worth asking Neovim developers.

Okay, that makes sense if it's a Neovim problem. I just assumed it may be with the colorscheme because of the previous highlighting problem from a couple weeks ago. Plus if I remember correctly I think the onedark and gruvbox8 schemes I used didn't have the issue. Thanks for looking at it though!
