### ISSUE TITLE
vt100

### ISSUE THREAD

**Issue by cipherlogs** [lifepillar/vim-solarized8#93]
I really like the minimal look of the B&W scheme

I'm using alacritty, how can I make the colorscheme use that B&W as the default one

Thank you.

**Comment by cipherlogs** [comment]
I have tried to set $TERM to "vt100" but I didn't notice any change.

also I have tried to hardcode t_Co to 2 and make all other if statements false only the one that I believe is for B&W
the colors got all messed up!

**Comment by lifepillar** [comment]
Somehow this issue slipped through the cracks and I failed to reply. Too bad. This is late in coming, and I apologize.

I have tried with Alacritty 0.12.1 and I can reproduce the issue: setting `t_Co` does not produce the desired outcome: it seems that some highlight groups change (visually), but most remain the same. I don't know why, I need to investigate further.

**Comment by lifepillar** [comment]
This works in Alacritty: run `vim --clean` then execute:

    :set rtp+=~/.vim/path/to/solarized8
    :colo solarized8
    :set t_Co=0

**Comment by lifepillar** [comment]
If `termguicolors` is set, it must be unset. So, this should fix this issue (for Vim):

```
set notermguicolors
set t_Co=0
colorscheme solarized8
```

In Neovim, however, there are some issues…

**Comment by cipherlogs** [comment]
Appreciate the reply, Thank you :)
