### ISSUE TITLE
Does not show truecolor with alacritty 

### ISSUE THREAD

**Issue by vivekvpandya** [lifepillar/vim-solarized8#94]

**Comment by lifepillar** [comment]
Yes it does.

**Comment by vivekvpandya** [comment]
![Screenshot from 2021-07-15 09-42-11](https://user-images.githubusercontent.com/5086212/125727872-9e337478-13bc-43b4-b6ce-9d8cee4517f5.png)

See in the image. I tried few hacks from Internet but nothing helps. Could you please help?

**Comment by lifepillar** [comment]
Is that within a Tmux session? If so, have you read the Troubleshooting session in the Readme?

If that doesn't fix it yet, please post a minimal configuration to reproduce your issue.

**Comment by vivekvpandya** [comment]
![Screenshot from 2021-07-15 11-09-36](https://user-images.githubusercontent.com/5086212/125734762-bb9a8317-e857-450e-8a7b-4ba8de28d42b.png)

I got upto this far with configuration shown in image. The output is same for gnome terminal and wihout tmux too.

**Comment by lifepillar** [comment]
Move the line `colorscheme solarized8` to the bottom of your script. Does that fix it?

**Comment by lifepillar** [comment]
Also, do not set `t_Co`.

**Comment by vivekvpandya** [comment]
No it does not ifx , instead it makes appear like very first screenshot.

**Comment by lifepillar** [comment]
I cannot reproduce your issue using Alacritty 0.8.0 and the following  `test-vimrc`:

```vim
syntax enable
set laststatus=2
set termguicolors
let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
set background=light
colorscheme solarized8
```

Run with `vim -N -i NONE -u test-vimrc`. Colors are fine both in my terminal and within tmux. Make sure your terminal supports true colors.

**Comment by vivekvpandya** [comment]
> I cannot reproduce your issue using Alacritty 0.8.0 and the following `test-vimrc`:
> 
> ```viml
> syntax enable
> set laststatus=2
> set termguicolors
> let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
> let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
> set background=light
> colorscheme solarized8
> ```
> 
> Run with `vim -N -i NONE -u test-vimrc`. Colors are fine both in my terminal and within tmux. Make sure your terminal supports true colors.

Thanks this works! however do you have any setting in tumx.conf ? I can't see expected output in vim within tmux.

**Comment by lifepillar** [comment]
>do you have any setting in tumx.conf

You may take a look at my [tmux.conf](https://github.com/lifepillar/dotfiles/blob/master/dot-tmux.conf). The only relevant setting is probably:

```
# Upgrade $TERM
set -g  default-terminal             "tmux-256color"
```

From `man tmux`:

```
     default-terminal terminal
             Set the default terminal for new windows created in this session - the default value of the TERM environment variable.  For tmux to work correctly,
             this must be set to `screen', `tmux' or a derivative of them.
```

**Comment by vivekvpandya** [comment]
Closing this issue as tmux issue is visible in gnome terminal too.
