### ISSUE TITLE
going back and forth to PaperColor breaks colors

### ISSUE THREAD

**Issue by paulharris** [lifepillar/vim-solarized8#96]
Hi,

Great work!

Colors look good if I start nvim-qt with the default color scheme,
and then do
:colo solarized8_high

If I then change to PaperColor and back again,
the "if" (in C code) doesn't get colored correctly anymore.

:colo PaperColor
:colo solarized8_high

so for "if (not something)"
the not will be colored, but "if" will not be.  It WAS colored...

**Comment by lifepillar** [comment]
I suppose you are experiencing a [well known long-standing Vim issue](https://github.com/vim/vim/issues/4405), which has been fixed some time ago.

Either upgrade Vim or set `let g:solarized_enable_extra_hi_groups = 0`.

**Comment by paulharris** [comment]
Ok thanks very much, that would explain it, I'm on Debian nvim 0.4.x
