### ISSUE TITLE
I really like the downgraded version. Make it available ?

### ISSUE THREAD

**Issue by cassepipe** [lifepillar/vim-solarized8#99]
I really like the downgraded version in 256 colors. It's actually the only colortheme I really like.
Would you consider making it available so I dont have to only support 256 colors ?

Or did you take inspiration from another theme for it ? Could you point me to it ?

**Comment by lifepillar** [comment]
If I understand correctly, you would like the palette that is used in 256-color terminals as the default palette. Right? Well, for that one would need to define a new color scheme, but it can certainly be done.

**Comment by lifepillar** [comment]
If you feel like hacking the color scheme yourself, this is what you can do:

1. open one of the template files in the `templates` folder (for example, `solarized8.colortemplate`) and edit the color palette definition. This is made of lines like the following:

```
Color: base02   #073642   236      0
```

You want to replace the hex color (e.g., `#073642`) with another hex color equivalent of the terminal color (`236` in the example above). To find the hex color equivalent of a terminal color, you may use `colortemplate#colorspace#xterm256_hexvalue()`. For instance:

```vim
echo colortemplate#colorspace#xterm256_hexvalue(236)
```

This will output a hex value, such as `#303030`. Then replace the hex color in the `Color` definition, e.g.:

```
Color: base02   #303030   236      0
```

Repeat for every color definition in the template, then rebuild the template. To build a template, you will need the [Colortemplate](https://github.com/lifepillar/vim-colortemplate/) plugin.

**Comment by cassepipe** [comment]
I'll give it a go. Thanks for taking the time to answer.
